/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Flags
  Available variables:
    These are macros. Do not use other than these
    flag name format: long-name[,short-name,...] (e.g: "flag-name,f")
    DEFINE_FLAG(type,name,default,flag_name,flag_func,flag_func_args...)
    WEB_FILTERED(filtered_flag_names...)
    DEFINE_BOOL_FLAG(name,default,flag_name,help)
    DEFINE_STRING_FLAG(name,default,flag_name,help,arg_description)
    DEFINE_INT_FLAG(name,type,default,flag_name,help,arg_description)
    BEGIN_MAP_FLAG(name,MappedType,default,flag_name,help)
      MAP_FLAG_ITEM(key,value) // repeat this line for each item
    END_MAP_FLAG()
    WEB_UI_NAME(ui_name)
    WEB_LSP_NAME(lsp_name)
    WEB_WORKER_NAME(worker_name)
    FILE_EXTENSIONS(file_ext...)
    CONFIG_MAP(config_name,flag_name)
    WEB_TYPE_MAP(flag_name,web_type)
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/

FILE_EXTENSIONS(".go");
WEB_UI_NAME("go3");
DEFINE_BOOL_FLAG(trust_input_len, false, "trust-input-len", "Trust input length so that use make([]byte,len). For production, check length for your safety threshold manually before reading array.");
DEFINE_INT_FLAG(safe_len_limit, std::uint64_t, 0, "safe-len-limit", "Safe vector length limit for []byte. default: 0 means infinity", "LEN");
DEFINE_STRING_FLAG(package_name, "", "package", "Package name for generated Go code", "NAME");
DEFINE_BOOL_FLAG(no_slice_io, false, "no-slice-io", "No sliced based io");
DEFINE_BOOL_FLAG(no_std_io, false, "no-std-io", "No standard io based io");
DEFINE_BOOL_FLAG(bytes_io, false, "bytes-io", "Generates *bytes.Buffer based io");
CONFIG_MAP("config.go.package", package_name);
DEFINE_BOOL_FLAG(visitor, false, "visitor", "Generates visitor pattern for each field");
