/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry_before_class
  Available Variables:
    ctx: Context_entry_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "ebmcodegen/stub/code_writer.hpp"
#include "ebmcodegen/stub/util.hpp"
#include "ebmgen/mapping.hpp"
namespace ebm2llvm {
    expected<std::pair<std::string, std::string>> to_llvm_op(Context_Expression_BINARY_OP& ctx) {
        switch (ctx.bop) {
            case ebm::BinaryOp::equal:
            case ebm::BinaryOp::not_equal:
            case ebm::BinaryOp::less:
            case ebm::BinaryOp::greater: {
                MAYBE(left_ty, ctx.get_field<"type">(ctx.left));
                MAYBE(type_str, ctx.visit(left_ty));
                auto kind = ctx.get_kind(left_ty);
                bool is_float = kind == ebm::TypeKind::FLOAT;
                bool is_signed = kind == ebm::TypeKind::INT;
                auto cmp = std::string(is_float ? "fcmp" : "icmp");
                switch (ctx.bop) {
                    case ebm::BinaryOp::equal:
                        return std::make_pair(cmp + " eq", type_str.to_string());
                    case ebm::BinaryOp::not_equal:
                        return std::make_pair(cmp + " ne", type_str.to_string());
                    case ebm::BinaryOp::less:
                        return std::make_pair(cmp + (is_float ? " olt" : (is_signed ? " slt" : " ult")), type_str.to_string());
                    case ebm::BinaryOp::greater:
                        return std::make_pair(cmp + (is_float ? " ogt" : (is_signed ? " sgt" : " ugt")), type_str.to_string());
                    default:
                        return std::make_pair("unknown_cmp", type_str.to_string());
                }
            }
            default:
                break;
        }
        auto kind = ctx.get_kind(ctx.type);
        bool is_float = kind == ebm::TypeKind::FLOAT;
        bool is_signed = kind == ebm::TypeKind::INT;
        MAYBE(llvm_type, ctx.visit(ctx.type));
        switch (ctx.bop) {
            case ebm::BinaryOp::add:
                return std::make_pair(is_float ? "fadd" : "add", llvm_type.to_string());
            case ebm::BinaryOp::sub:
                return std::make_pair(is_float ? "fsub" : "sub", llvm_type.to_string());
            case ebm::BinaryOp::mul:
                return std::make_pair(is_float ? "fmul" : "mul", llvm_type.to_string());
            case ebm::BinaryOp::div:
                if (is_float) return std::make_pair("fdiv", llvm_type.to_string());
                return std::make_pair(is_signed ? "sdiv" : "udiv", llvm_type.to_string());
            case ebm::BinaryOp::mod:
                if (is_float) return std::make_pair("frem", llvm_type.to_string());
                return std::make_pair(is_signed ? "srem" : "urem", llvm_type.to_string());
            default:
                return std::make_pair("unknown", llvm_type.to_string());
        }
    }

    struct DebugInfoManager {
        ebmgen::MappingTable& mod;
        // LLVMのメタデータIDとスコープを管理する最小単位
        struct DebugContext {
            int unit_id = 0;        // DICompileUnit
            int file_id = 1;        // DIFile
            int subprogram_id = 2;  // DISubprogram
        } ctx;

        // キャッシュキーを line << 16 | col に詰め込んで map の負荷を減らす（簡易版）
        std::unordered_map<std::uint32_t, int> loc_cache;
        int next_id = 3;  // 0, 1, 2 は基本構造で使用済み

       public:
        // 命令生成時のロケーション付与
        template <ebmgen::AnyRef T>
        std::string get_dbg(T node) {
            auto loc = mod.get_debug_loc(to_any_ref(node));
            if (!loc) return "";  // デバッグ情報なし
            uint32_t key = (static_cast<std::uint32_t>(loc->line.value()) << 16) | (loc->column.value() & 0xFFFF);
            if (loc_cache.find(key) == loc_cache.end()) {
                int id = next_id++;
                // スコープは常に現在の関数 (!2) を指す
                loc_cache[key] = id;
                append_metadata(id, *loc);
            }
            return " !dbg !" + std::to_string(loc_cache[key]);
        }

       private:
        CodeWriter metadata_buffer;
        void append_metadata(int id, const ebm::Loc& loc) {
            metadata_buffer.writeln("!", std::to_string(id), " = !DILocation(line: ", std::to_string(loc.line.value()), ", column: ", std::to_string(loc.column.value()), ", scope: !", std::to_string(ctx.subprogram_id), ")");
        }
    };
}  // namespace ebm2llvm

DEFINE_VISITOR(entry_before) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    ctx.config().bool_type = "i1";
    ctx.config().int_prefix = "i";
    ctx.config().uint_prefix = "i";
    ctx.config().usize_type_name = "i64";

    ctx.config().loop_statement_custom = [](Context_Statement_LOOP_STATEMENT& ctx) -> expected<Result> {
        if (!is_nil(ctx.loop.lowered_statement.id)) {
            return ctx.visit(ctx.loop.lowered_statement.id);
        }
        CodeWriter w;
        if (auto init = ctx.loop.init()) {
            MAYBE(init_str, ctx.visit(*init));
            w.write(std::move(init_str.to_writer()));
        }
        auto start_label = std::format(".L.start.{}", ctx.config().next_reg());
        auto cond_label = std::format(".L.cond.{}", ctx.config().next_reg());
        auto body_label = std::format(".L.body.{}", ctx.config().next_reg());
        auto end_label = std::format(".L.end.{}", ctx.config().next_reg());
        w.writeln("br label %", start_label);
        w.writeln_noindent(start_label, ":");
        if (auto cond = ctx.loop.condition()) {
            auto added = ctx.add_writer();
            MAYBE(cond_str, ctx.visit(cond->cond));
            w.write(std::move(ctx.get_writer()->get()));
            w.writeln("br i1 ", cond_str.to_writer(), ", label %", body_label, ", label %", end_label);
            w.writeln_noindent(body_label, ":");
        }
        MAYBE(body_str, ctx.visit(ctx.loop.body));
        w.write(std::move(body_str.to_writer()));
        if (auto step = ctx.loop.increment()) {
            MAYBE(step_str, ctx.visit(*step));
            w.write(std::move(step_str.to_writer()));
        }
        w.writeln("br label %", start_label);
        w.writeln_noindent(end_label, ":");
        return w;
    };

    ctx.config().if_statement_custom = [](Context_Statement_IF_STATEMENT& ctx) -> expected<Result> {
        MAYBE(if_thens, flatten_if_then(ctx, ctx.item_id));
        auto final_label = std::format(".L.{}", ctx.config().next_reg());
        CodeWriter output;
        std::string next_label = std::format(".L.{}", ctx.config().next_reg());
        for (size_t i = 0; i < if_thens.size(); i++) {
            const auto& if_then = if_thens[i];
            if (if_then.condition) {
                auto then_label = next_label;
                auto else_label = i != if_thens.size() - 1 ? std::format(".L.{}", ctx.config().next_reg()) : final_label;
                auto added = ctx.add_writer();
                MAYBE(cond_str, ctx.visit(*if_then.condition));
                output.write(std::move(ctx.get_writer()->get()));
                output.writeln("br i1 ", cond_str.to_writer(), ", label %", then_label, ", label %", else_label);
                output.writeln_noindent(then_label, ":");
                MAYBE(then_str, ctx.visit(if_then.then_branch));
                output.write(std::move(then_str.to_writer()));
                output.writeln("br label %", final_label);
                next_label = else_label;
            }
            else {
                auto added = ctx.add_writer();
                MAYBE(else_str, ctx.visit(if_then.then_branch));
                output.write(std::move(else_str.to_writer()));
                output.writeln("br label %", final_label);
            }
        }
        output.writeln_noindent(final_label, ":");
        return output;
    };

    ctx.config().variable_decl_custom = [](Context_Statement_VARIABLE_DECL& ctx) -> expected<Result> {
        CodeWriter output;
        auto var_name = "%" + ctx.identifier();
        MAYBE(llvm_type, ctx.visit(ctx.var_decl.var_type));
        ctx.config().function_local_variables.writeln(var_name, " = alloca ", llvm_type.to_writer());
        if (!is_nil(ctx.var_decl.initial_value)) {
            auto added = ctx.add_writer();
            MAYBE(init_val, ctx.visit(ctx.var_decl.initial_value));
            output.write(std::move(ctx.get_writer()->get()));
            output.writeln("store ", llvm_type.to_writer(), " ", init_val.to_writer(), ", ptr ", var_name);
        }
        return output;
    };

    ctx.config().identifier_custom = [](Context_Expression_IDENTIFIER& ctx) -> expected<Result> {
        if (ctx.is(ebm::StatementKind::PARAMETER_DECL, ctx.id)) {
            return "%" + ctx.identifier(ctx.id);
        }
        // load
        MAYBE(got, ctx.get_writer());
        auto var_name = "%" + ctx.identifier(ctx.id);
        MAYBE(llvm_type, ctx.visit(ctx.type));
        auto tmp = std::format("%t{}", ctx.config().next_reg());
        got.get().writeln(tmp, " = load ", llvm_type.to_writer(), ", ptr ", var_name);
        return tmp;
    };

    ctx.config().param_visitor = [](Context_Statement_PARAMETER_DECL& ctx, Result type) -> expected<Result> {
        auto param_name = "%" + ctx.identifier();
        return CODE(type.to_writer(), " ", param_name);
    };

    ctx.config().assignment_custom = [](Context_Statement_ASSIGNMENT& ctx) -> expected<Result> {
        CodeWriter w;
        MAYBE(target, ctx.get(ctx.target));
        if (target.body.kind == ebm::ExpressionKind::IDENTIFIER) {
            auto var_name = "%" + ctx.identifier(*target.body.id());
            auto added = ctx.add_writer();
            MAYBE(value_str, ctx.visit(ctx.value));
            w.write(std::move(ctx.get_writer()->get()));
            MAYBE(type, ctx.get_field<"type">(ctx.target));
            MAYBE(llvm_type, ctx.visit(type));
            w.writeln("store ", llvm_type.to_writer(), " ", value_str.to_writer(), ", ptr ", var_name);
            return w;
        }
        return unexpect_error("unsupported assignment target: {}", to_string(target.body.kind));
    };

    ctx.config().function_decl_custom = [](Context_Statement_FUNCTION_DECL& ctx) -> expected<Result> {
        CodeWriter output;
        auto func_name = "@" + ctx.identifier(ctx.item_id);
        MAYBE(return_type, ctx.visit(ctx.func_decl.return_type));
        output.write("define ", return_type.to_writer(), " ", func_name, "(");
        for (size_t i = 0; i < ctx.func_decl.params.container.size(); i++) {
            MAYBE(param, ctx.visit(ctx.func_decl.params.container[i]));
            output.write(std::move(param.to_writer()));
            if (i != ctx.func_decl.params.container.size() - 1) {
                output.write(", ");
            }
        }
        output.writeln(") {");
        output.writeln("entry:");
        {
            auto scope = output.indent_scope();
            MAYBE(body, ctx.visit(ctx.func_decl.body));
            output.write(std::move(ctx.config().function_local_variables));
            output.write(std::move(body.to_writer()));
        }
        output.writeln("}");
        return output;
    };

    ctx.config().type_cast_custom = [](Context_Expression_TYPE_CAST& ctx) -> expected<Result> {
        MAYBE(got, ctx.get_writer());
        MAYBE(value_str, ctx.visit(ctx.type_cast_desc.source_expr));
        MAYBE(from_type, ctx.visit(ctx.type_cast_desc.from_type));
        MAYBE(to_type, ctx.visit(ctx.type));
        MAYBE(type_info, ctx.get(ctx.type_cast_desc.from_type));
        if (ctx.type_cast_desc.cast_kind == ebm::CastType::LARGE_INT_TO_SMALL_INT) {  // trunc
            auto tmp = std::format("%t{}", ctx.config().next_reg());
            got.get().writeln(tmp, " = trunc ", from_type.to_writer(), " ", value_str.to_writer(), " to ", to_type.to_writer());
            return tmp;
        }
        else if (ctx.type_cast_desc.cast_kind == ebm::CastType::SMALL_INT_TO_LARGE_INT) {  // zext or sext
            auto tmp = std::format("%t{}", ctx.config().next_reg());
            bool is_signed = type_info.body.kind == ebm::TypeKind::INT;
            got.get().writeln(tmp, " = ", is_signed ? "sext" : "zext", " ", from_type.to_writer(), " ", value_str.to_writer(), " to ", to_type.to_writer());
            return tmp;
        }
        else if (ctx.type_cast_desc.cast_kind == ebm::CastType::USIZE_TO_INT) {  // usize is i64 so ext or trunc
            MAYBE(to_type_info, ctx.get(ctx.type));
            MAYBE(size, to_type_info.body.size());
            if (size.value() < 64) {
                auto tmp = std::format("%t{}", ctx.config().next_reg());
                got.get().writeln(tmp, " = trunc ", from_type.to_writer(), " ", value_str.to_writer(), " to ", to_type.to_writer());
                return tmp;
            }
            if (size.value() > 64) {
                auto tmp = std::format("%t{}", ctx.config().next_reg());
                bool is_signed = type_info.body.kind == ebm::TypeKind::INT;
                got.get().writeln(tmp, " = ", is_signed ? "sext" : "zext", " ", from_type.to_writer(), " ", value_str.to_writer(), " to ", to_type.to_writer());
                return tmp;
            }
            // size == 64, so no cast needed
            return value_str;
        }
        return value_str;  // TODO: support other
    };

    ctx.config().return_visitor = [](Context_Statement_RETURN& ctx) -> expected<Result> {
        CodeWriter output;
        if (is_nil(ctx.value)) {
            output.writeln("ret void");
        }
        else {
            auto added = ctx.add_writer();
            MAYBE(ret_val, ctx.visit(ctx.value));
            output.write(std::move(ctx.get_writer()->get()));
            MAYBE(type, ctx.get_field<"type">(ctx.value));
            MAYBE(llvm_type, ctx.visit(type));
            output.writeln("ret ", llvm_type.to_writer(), " ", ret_val.to_writer());
        }
        return output;
    };

    ctx.config().binary_op_custom = [](Context_Expression_BINARY_OP& ctx) -> expected<Result> {
        // 1. 親の Writer（出力先）を確保
        MAYBE(output, ctx.get_writer());

        // 2. 子ノードを visit して「オペランド文字列」を取得
        // リテラルなら "1", "41" が、入れ子の演算なら "%t0" などが返ってくる
        MAYBE(left_val, ctx.visit(ctx.left));
        MAYBE(right_val, ctx.visit(ctx.right));

        // 3. この演算結果を格納する新しいレジスタ名を生成
        // ※ global_reg_count++ を利用した名前付きレジスタ（例: %t10）
        std::string result_reg = std::format("%t{}", ctx.config().next_reg());

        // 4. 型情報の取得（ソース言語の i32 -> LLVM の "i32"）

        // 5. 命令の選択（+ -> add, - -> sub など）
        MAYBE(llvm_op, to_llvm_op(ctx));
        auto& llvm_op_str = llvm_op.first;
        auto& llvm_type_str = llvm_op.second;

        // 6. LLVM IR 命令の書き出し
        // フォーマット: "%res = op type lhs, rhs"
        output.get().writeln(result_reg, " = ", llvm_op_str, " ", llvm_type_str, " ",
                             left_val.to_writer(), ", ", right_val.to_writer());

        // 7. 親ノードには「結果が入っているレジスタ名」を返す
        return result_reg;
    };

    return pass;
}
