/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: Statement_CONTINUE_class
  Available Variables:
    ctx: Context_Statement_CONTINUE
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      continue_: const ebm::LoopFlowControl&
        related_statement: WeakStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/


#include "../codegen.hpp"
DEFINE_VISITOR(Statement_CONTINUE) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (ctx.config().loop_labels.empty()) {
        return unexpect_error("llvm continue: not inside a loop");
    }
    CodeWriter w;
    w.writeln("br label %", ctx.config().loop_labels.back().first);
    return w;
}

