version: 2
updates:
  # Maintain dependence for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependence for golang
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/web/doc"
    schedule:
      interval: "weekly"
  
  
  - package-ecosystem: "npm"
    directory: "/lsp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/web/dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/ast2rust"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/src/tool/json2rust"
    schedule:
      interval: "weekly"
