version: 2
updates:
  # Maintain dependence for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependence for golang
  - package-ecosystem: "gomod"
    directory: "/**"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/**"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/**"
    schedule:
      interval: "weekly"