export const enum ElementID {
    CONTAINER1 = "container1",
    CONTAINER2 = "container2",
    TITLE_BAR = "title_bar",
    LANGUAGE_SELECT = "language-select",
    COPY_BUTTON = "copy-button",
    GITHUB_LINK = "github-link",
    BALL = "ball",
    BALL_BOUND = "ball-bound",
    INPUT_LIST = "input-list",
}

export const enum ConfigKey {
    COMMON_FILE_NAME ="file_name",
    COMMON_SAVE_LOCATION = "save_url",
    CPP_SOURCE_MAP = "source_map", 
    CPP_EXPAND_INCLUDE = "expand_include",
    CPP_USE_ERROR = "use_error",
    CPP_USE_RAW_UNION = "use_raw_union",
    CPP_CHECK_OVERFLOW = "check_overflow",
    CPP_COMPILE_VIA_API = "compile_via_api",
    GO_OMIT_MUST_ENCODE = "omit_must_encode",
    GO_OMIT_DECODE_EXACT = "omit_decode_exact",
    GO_OMIT_VISITOR= "omit_visitors",
    GO_OMIT_MARSHAL_JSON = "omit_marshal_json",
    TS_JAVASCRIPT = "javascript",
    C_MULTI_FILE = "multi_file",
    C_OMIT_ERROR_CALLBACK = "omit_error",
    C_USE_MEMCPY = "use_memcpy",
    C_ZERO_COPY = "zero_copy",
}