/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: entry_before_class
  Available Variables:
    ctx: Context_entry_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/


#include <format>
#include <string>
#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "escape/escape.h"

namespace CODEGEN_NAMESPACE {

    // Scala runs on the JVM and shares Java's integer model: no unsigned
    // types. uintN maps to the smallest signed type holding all values
    // losslessly: N <= 31 -> Int, otherwise Long (u64 wraps into Long;
    // unsigned comparisons/divisions go through java.lang.Long helpers).
    // intN maps to Int for N <= 32, Long otherwise.
    inline bool scala_uint_is_int(std::uint64_t bits) {
        return bits <= 31;
    }
    inline bool scala_int_is_int(std::uint64_t bits) {
        return bits <= 32;
    }

    // Boxed forms for OPTIONAL/PTR of a value type: null must be
    // representable. Scala's Predef implicit conversions (int2Integer /
    // Integer2int etc.) keep assignments and arithmetic working.
    inline std::string scala_box_type(const std::string& t) {
        if (t == "Int") {
            return "java.lang.Integer";
        }
        if (t == "Long") {
            return "java.lang.Long";
        }
        if (t == "Boolean") {
            return "java.lang.Boolean";
        }
        if (t == "Float") {
            return "java.lang.Float";
        }
        if (t == "Double") {
            return "java.lang.Double";
        }
        return t;
    }

    // True when the expression is an ARRAY/VECTOR of u8 (rendered Array[Byte]).
    inline bool scala_expr_is_u8_array(auto& ctx, const ebm::ExpressionRef& expr_ref) {
        auto expr = ctx.get(expr_ref);
        if (!expr) {
            return false;
        }
        auto t = ctx.get(expr->body.type);
        if (!t) {
            return false;
        }
        if (t->body.kind != ebm::TypeKind::ARRAY && t->body.kind != ebm::TypeKind::VECTOR) {
            return false;
        }
        auto elem = t->body.element_type();
        return elem && is_u8(ctx, *elem);
    }

    // ARRAY/VECTOR type text: u8 element -> Array[Byte], otherwise
    // Array[<elem>]. Scala's bracket syntax is compositional, so nested
    // arrays need no special handling.
    inline expected<Result> scala_array_type(auto& ctx, ebm::TypeRef element_type) {
        if (is_u8(ctx, element_type)) {
            return Result("Array[Byte]");
        }
        MAYBE(elem, ctx.visit(element_type));
        return CODE("Array[", elem.to_writer(), "]");
    }

    // Structs live flat in the top-level object (Scala classes nested in a
    // class capture the outer instance, unlike Java's static nested classes),
    // so nested/anonymous struct names join their layer path with "_".
    inline expected<Result> scala_layer_name(auto& ctx) {
        MAYBE(name, get_identifier_layer_str(ctx, from_weak(ctx.id), "_"));
        return Result(name);
    }

    inline std::optional<ebm::FunctionKind> scala_related_fn_kind(auto& ctx, const ebm::WeakStatementRef& related) {
        if (is_nil(related)) {
            return std::nullopt;
        }
        auto fn = ctx.template get_field<"func_decl">(related.id);
        if (!fn) {
            return std::nullopt;
        }
        return fn->kind;
    }

    // Scala 3 dropped implicit numeric widening (Java auto-promotes int ->
    // long): a getter whose return type is the VARIANT common type (Long)
    // returning an Int arm field is a type error. Returns the .toX conversion
    // that makes the return conform; identity conversions (.toLong on Long)
    // are harmless. Mirrors ebm2java's java_boxing_cast, resolving through
    // OPTIONAL/PTR (boxed) and VARIANT common types.
    inline std::optional<std::string> scala_widening_suffix(auto& ctx, ebm::TypeRef ret_type_ref) {
        auto t = ctx.get(ret_type_ref);
        if (!t) {
            return std::nullopt;
        }
        if (t->body.kind == ebm::TypeKind::OPTIONAL) {
            if (auto inner = t->body.inner_type()) {
                t = ctx.get(*inner);
            }
        }
        else if (t->body.kind == ebm::TypeKind::PTR) {
            if (auto inner = t->body.pointee_type()) {
                t = ctx.get(*inner);
            }
        }
        if (!t) {
            return std::nullopt;
        }
        if (t->body.kind == ebm::TypeKind::VARIANT) {
            auto vd = t->body.variant_desc();
            if (!vd || is_nil(vd->common_type)) {
                return std::nullopt;
            }
            t = ctx.get(vd->common_type);
            if (!t) {
                return std::nullopt;
            }
        }
        std::uint64_t bits = 0;
        if (auto sz = t->body.size()) {
            bits = sz->value();
        }
        switch (t->body.kind) {
            case ebm::TypeKind::UINT:
                return scala_uint_is_int(bits) ? ".toInt" : ".toLong";
            case ebm::TypeKind::INT:
                return scala_int_is_int(bits) ? ".toInt" : ".toLong";
            case ebm::TypeKind::USIZE:
                return ".toLong";
            case ebm::TypeKind::FLOAT:
                return bits <= 32 ? ".toFloat" : ".toDouble";
            default:
                return std::nullopt;
        }
    }

    // True when the type renders as Any (untyped union storage).
    inline bool scala_renders_any(auto& ctx, ebm::TypeRef type_ref) {
        auto t = ctx.get(type_ref);
        if (!t) {
            return false;
        }
        if (t->body.kind == ebm::TypeKind::STRUCT_UNION || t->body.kind == ebm::TypeKind::META) {
            return true;
        }
        if (t->body.kind == ebm::TypeKind::VARIANT) {
            auto vd = t->body.variant_desc();
            return !vd || is_nil(vd->common_type);
        }
        return false;
    }

    // Scala has no break/continue: scan a loop body for BREAK/CONTINUE to
    // decide whether loop_statement_custom must wrap it in the
    // BgnBreakEx/BgnContinueEx try/catch scaffold. Nested loops handle their
    // own control flow, so the scan does not descend into LOOP_STATEMENT.
    inline bool scala_has_ctrl(auto&& ctx, const ebm::StatementRef& ref, ebm::StatementKind target) {
        auto stmt = ctx.get(ref);
        if (!stmt) {
            return false;
        }
        if (stmt->body.kind == target) {
            return true;
        }
        switch (stmt->body.kind) {
            case ebm::StatementKind::LOOP_STATEMENT:
                return false;
            case ebm::StatementKind::BLOCK: {
                auto blk = stmt->body.block();
                if (!blk) {
                    return false;
                }
                for (auto& child : blk->container) {
                    if (scala_has_ctrl(ctx, child, target)) {
                        return true;
                    }
                }
                return false;
            }
            case ebm::StatementKind::IF_STATEMENT: {
                auto ifs = stmt->body.if_statement();
                if (!ifs) {
                    return false;
                }
                if (scala_has_ctrl(ctx, ifs->then_block, target)) {
                    return true;
                }
                if (!is_nil(ifs->else_block) && scala_has_ctrl(ctx, ifs->else_block, target)) {
                    return true;
                }
                return false;
            }
            case ebm::StatementKind::MATCH_STATEMENT: {
                auto m = stmt->body.match_statement();
                if (m && !is_nil(m->lowered_if_statement.id)) {
                    return scala_has_ctrl(ctx, m->lowered_if_statement.id, target);
                }
                return false;
            }
            default:
                return false;
        }
    }

    // Embedded IO/error runtime, emitted once at the top of the outer object.
    // Scalar (multi-byte integer/float) IO never reaches the backend as a
    // plain READ_DATA/WRITE_DATA: ebmgen always attaches a lowered statement
    // (readBytes + shift composition), so the runtime only provides the
    // byte-level primitives the lowered/bytes paths actually call.
    // BgnBreak/BgnContinue are the ControlThrowable singletons thrown by the
    // BREAK/CONTINUE hooks and caught by the loop scaffold.
    inline const char* scala_runtime_source() {
        return R"(final class BgnError(msg: java.lang.String) extends java.lang.RuntimeException(msg)
final class BgnBreakEx extends scala.util.control.ControlThrowable
val BgnBreak = new BgnBreakEx
final class BgnContinueEx extends scala.util.control.ControlThrowable
val BgnContinue = new BgnContinueEx
final class BgnInput(var buf: Array[Byte]) {
  var offset: Int = 0
  def remaining(): Long = (buf.length - offset).toLong
  private def require_(n: Int): Unit = {
    if (n < 0 || offset + n > buf.length) {
      throw new BgnError("unexpected EOF: need " + n + " bytes at offset " + offset)
    }
  }
  def readBytes(n: Long): Array[Byte] = {
    val len = n.toInt
    require_(len)
    val r = java.util.Arrays.copyOfRange(buf, offset, offset + len)
    offset += len
    r
  }
  def readRemaining(): Array[Byte] = readBytes(remaining())
}
final class BgnOutput {
  var buf: Array[Byte] = new Array[Byte](64)
  var offset: Int = 0
  private def ensure(n: Int): Unit = {
    if (offset + n > buf.length) {
      var cap = buf.length * 2
      if (cap < offset + n) { cap = offset + n }
      buf = java.util.Arrays.copyOf(buf, cap)
    }
  }
  def writeBytes(b: Array[Byte], n: Long): Unit = {
    val len = n.toInt
    ensure(len)
    System.arraycopy(b, 0, buf, offset, len)
    offset += len
  }
  def toBytes(): Array[Byte] = java.util.Arrays.copyOf(buf, offset)
}
def append(a: Array[Byte], v: Long): Array[Byte] = { val r = java.util.Arrays.copyOf(a, a.length + 1); r(a.length) = v.toByte; r }
def append(a: Array[Int], v: Long): Array[Int] = { val r = java.util.Arrays.copyOf(a, a.length + 1); r(a.length) = v.toInt; r }
def append(a: Array[Long], v: Long): Array[Long] = { val r = java.util.Arrays.copyOf(a, a.length + 1); r(a.length) = v; r }
def append(a: Array[Float], v: Double): Array[Float] = { val r = java.util.Arrays.copyOf(a, a.length + 1); r(a.length) = v.toFloat; r }
def append(a: Array[Double], v: Double): Array[Double] = { val r = java.util.Arrays.copyOf(a, a.length + 1); r(a.length) = v; r }
def append(a: Array[Boolean], v: Boolean): Array[Boolean] = { val r = java.util.Arrays.copyOf(a, a.length + 1); r(a.length) = v; r }
def append[T <: scala.AnyRef](a: Array[T], v: T): Array[T] = { val r = java.util.Arrays.copyOf(a, a.length + 1); r(a.length) = v; r }
)";
    }

}  // namespace CODEGEN_NAMESPACE

DEFINE_VISITOR(entry_before) {
    using namespace CODEGEN_NAMESPACE;
    auto& config = ctx.config();

    // Block / statement framing. Trailing semicolons are always legal in
    // Scala and remove every newline-continuation ambiguity, so the
    // imperative stage keeps them.
    config.begin_block = "{";
    config.end_block = "}";
    config.endof_statement = ";";
    config.use_brace_for_condition = true;
    config.metadata_comment_prefix = "//";
    config.metadata_comment_suffix = "";
    config.self_value = "this";
    config.bool_true = "true";
    config.bool_false = "false";
    config.bool_type = "Boolean";
    config.void_type = "Unit";
    config.meta_type_name = "Any";
    config.setter_status_ok = "true";
    config.setter_status_failure = "false";
    config.property_setter_return_type = "Boolean";

    // ADR 0008/0039: absolute-offset companion increment line.
    config.runtime_offset_add_prefix = "runtime_state.offset += (";
    config.runtime_offset_add_suffix = ");";

    // Struct = class at the outer-object level; methods live inside the
    // class body. Anonymous (generator-numbered) variant-arm classes are
    // private to the object: the public surface carries only names the .bgn
    // author wrote.
    config.struct_definition_start_wrapper = [](Context_Statement_STRUCT_DECL& sctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        // Object-scoped private (not class-private): sibling classes and the
        // parent format reference the arm classes.
        std::string visibility = is_nil(sctx.struct_decl.name)
                                     ? "private[" + std::string(sctx.flags().object_name) + "] "
                                     : "";
        // The declared name must match how struct_type_custom renders
        // references: the "_"-joined layer path (classes are flat in the
        // outer object).
        MAYBE(name, get_identifier_layer_str(sctx, sctx.item_id, "_"));
        w.writeln(visibility, "class ", name, " {");
        return w;
    };
    config.methods_inner_class = true;
    // Anon variant-arm structs get their property accessors hoisted onto the
    // parent format: the accessor bodies reference sibling fields of the
    // outer instance (`this.header`, the union storage), which do not exist
    // on the arm class.
    config.relocate_anon_inner_properties = true;

    // Members of the outer object are visible from every class in it; no
    // modifier needed for inlined imported toplevel variables.
    config.imported_toplevel_variable_modifier = "";

    // Variables / parameters: `var name : Type = init` / `name : Type`.
    // The space before the colon is load-bearing: reserved identifiers are
    // suffixed with "_" (type -> type_), and Scala lexes a trailing
    // underscore followed by an opchar as ONE identifier (`type_:` is a
    // valid identifier), so `var type_: Int` fails to parse.
    config.variable_with_type = true;
    config.variable_name_prior_to_type = true;
    config.variable_type_separator = " :";
    config.variable_initializer = "=";
    config.variable_define_keyword = "var";
    config.immutable_variable_define_keyword = "val";
    config.constant_define_keyword = "val";
    config.constant_initializer = "=";
    config.parameter_name_prior_to_type = true;
    config.param_type_separator = " : ";

    // Enums render as val constants in an object (see enum_decl_visitor);
    // the enum *type* is its base integer type. use_base_type_of_enum covers
    // typed enums, enum_type_name_wrapper the nil-base fallback.
    config.use_base_type_of_enum = true;
    config.enum_type_name_wrapper = [](Result) -> expected<Result> {
        return Result("Int");
    };
    config.enum_member_accessor = ".";

    config.usize_type_name = "Long";
    config.encoder_return_type = "Unit";
    config.decoder_return_type = "Unit";
    config.encoder_input_type = "BgnOutput";
    config.decoder_input_type = "BgnInput";
    config.default_value_option.pointer_init = "null";
    config.default_value_option.optional_init = "null";
    config.default_value_option.bytes_init = "new Array[Byte](0)";
    config.default_value_option.encoder_return_init = "null";
    config.default_value_option.decoder_return_init = "null";

    // Type mappings
    config.make_int_type = [](size_t bits) -> expected<Result> {
        return Result(scala_int_is_int(bits) ? "Int" : "Long");
    };
    config.make_uint_type = [](size_t bits) -> expected<Result> {
        return Result(scala_uint_is_int(bits) ? "Int" : "Long");
    };
    config.make_float_type = [](size_t bits) -> expected<Result> {
        return Result(bits <= 32 ? "Float" : "Double");
    };
    config.optional_type_wrapper = [](Result elem) -> expected<Result> {
        return Result(scala_box_type(elem.to_string()));
    };
    config.pointer_type_wrapper = [](Result elem) -> expected<Result> {
        return Result(scala_box_type(elem.to_string()));
    };
    config.make_pointer_wrapper = [](Result elem) -> expected<Result> { return elem; };
    config.make_optional_wrapper = [](Result elem) -> expected<Result> { return elem; };
    config.array_type_wrapper = [](Context_Type_ARRAY& actx) -> expected<Result> {
        return scala_array_type(actx, actx.element_type);
    };
    config.vector_type_wrapper = [](Context_Type_VECTOR& vctx) -> expected<Result> {
        return scala_array_type(vctx, vctx.element_type);
    };
    config.variant_type_custom = [](Context_Type_VARIANT& vctx) -> expected<Result> {
        if (is_nil(vctx.variant_desc.common_type)) {
            return Result("Any");
        }
        return pass;  // default resolves the common type
    };
    config.struct_union_type_custom = [](Context_Type_STRUCT_UNION&) -> expected<Result> {
        return Result("Any");
    };
    config.struct_type_custom = [](Context_Type_STRUCT& sctx) -> expected<Result> {
        return scala_layer_name(sctx);
    };
    config.recursive_struct_type_custom = [](Context_Type_RECURSIVE_STRUCT& sctx) -> expected<Result> {
        return scala_layer_name(sctx);
    };

    // Fields: `var name: Type = default;` -- inline defaults so nested struct
    // decode (`this.field.decode(r)`) never hits null. Scala class fields
    // require an initializer; null.asInstanceOf[T] is the total fallback
    // (0 for value types, null for reference types).
    config.field_decl_custom = [](Context_Statement_FIELD_DECL& fctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (fctx.field_decl.is_state_variable()) {
            return Result{};
        }
        auto name = fctx.identifier();
        CodeWriter w;
        // STRUCT_UNION fields carry their variant-arm struct decls; hoist the
        // arm classes to the outer-object level (Scala classes nested in a
        // class would capture the outer instance).
        MAYBE(struct_members, struct_union_members(fctx, fctx.field_decl.field_type));
        for (auto& member : struct_members) {
            fctx.config().decl_toplevel.push_back(std::move(member.second.to_writer()));
        }
        MAYBE(type, fctx.visit(fctx.field_decl.field_type));
        MAYBE(default_, as_DEFAULT_VALUE(fctx, fctx.field_decl.field_type));
        auto default_txt = default_.to_string();
        // Generator-numbered storage (union fields etc.) is private; access
        // goes through the property accessors.
        // Scala `private` is class-scoped (Java's is outer-class-scoped);
        // the parent format's methods poke arm storage directly, so scope to
        // the enclosing object instead.
        std::string visibility = is_nil(fctx.field_decl.name)
                                     ? "private[" + std::string(fctx.flags().object_name) + "] "
                                     : "";
        if (default_txt.empty()) {
            w.writeln(visibility, "var ", name, " : ", type.to_writer(), " = null.asInstanceOf[", type.to_writer(), "];");
        }
        else {
            w.writeln(visibility, "var ", name, " : ", type.to_writer(), " = ", default_txt, ";");
        }
        return w;
    };

    // Functions: `[private ]def <name>(<params>): <ret> = {`. Object-level
    // (static) and instance methods share the same syntax in Scala.
    config.function_definition_start_wrapper = [](Result return_type, std::string_view name, CodeWriter params, Context_Statement_FUNCTION_DECL& fctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        auto ret = return_type.to_string();
        if (ret.empty()) {
            ret = "Unit";
        }
        std::string emit_name(name);
        std::string visibility = "";
        // Hoisted anon-inner accessors live on parent_format; prefix with the
        // inner struct identifier so sibling accessors don't collide. They
        // are implementation details of the outer property dispatcher, so
        // keep them off the public surface (object-scoped, not class-scoped:
        // the property dispatcher may sit on a different class).
        if (auto inner = hoisted_accessor_inner_ident(fctx)) {
            emit_name = *inner + "_" + emit_name;
            visibility = "private[" + std::string(fctx.flags().object_name) + "] ";
        }
        w.writeln(visibility, "def ", emit_name, "(", params, ") : ", ret, " = {");
        return w;
    };

    // Errors are exceptions: never materialize `if (IS_ERROR(x))` guards.
    config.skip_is_error_if_statement = true;
    config.is_error_visitor = [](Context_Expression_IS_ERROR&) -> expected<Result> {
        return Result("false");
    };
    config.error_return_visitor = [](Context_Statement_ERROR_RETURN& rctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(err, rctx.visit(rctx.value));
        auto txt = err.to_string();
        CodeWriter w;
        if (txt.empty() || txt == "null") {
            w.writeln("throw new BgnError(\"error\");");
        }
        else {
            w.writeln("throw new BgnError(\"\" + (", txt, "));");
        }
        return w;
    };
    config.error_report_visitor = [](Context_Statement_ERROR_REPORT& rctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(lit, rctx.get(rctx.error_report.message));
        auto text = futils::escape::escape_str<std::string>(lit.body.data);
        CodeWriter w;
        w.writeln("throw new BgnError(\"", text, "\");");
        return w;
    };

    // RETURN: encode/decode are Unit; their EBM return value is the "null"
    // encoder/decoder-return placeholder, and `return null` in a Unit def
    // trips the discarded-value warning. A wrapper's `return impl(...)` CALL
    // must still run, so it is emitted as a statement before the bare return.
    config.return_visitor = [](Context_Statement_RETURN& rctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        auto fn_kind = scala_related_fn_kind(rctx, rctx.related_function);
        const bool codec = fn_kind && (*fn_kind == ebm::FunctionKind::ENCODE || *fn_kind == ebm::FunctionKind::DECODE);
        if (codec) {
            if (!is_nil(rctx.value)) {
                auto vexpr = rctx.get(rctx.value);
                if (vexpr && vexpr->body.kind == ebm::ExpressionKind::CALL) {
                    MAYBE(val, rctx.visit(rctx.value));
                    w.writeln(val.to_string(), ";");
                }
            }
            w.writeln("return;");
            return w;
        }
        if (is_nil(rctx.value)) {
            w.writeln("return;");
            return w;
        }
        MAYBE(val, rctx.visit(rctx.value));
        auto txt = val.to_string();
        if (txt.empty()) {
            w.writeln("return;");
            return w;
        }
        if (txt != "null" && !is_nil(rctx.related_function)) {
            auto fn = rctx.template get_field<"func_decl">(rctx.related_function.id);
            if (fn) {
                if (auto conv = scala_widening_suffix(rctx, fn->return_type)) {
                    w.writeln("return (", txt, ")", *conv, ";");
                    return w;
                }
            }
        }
        w.writeln("return ", txt, ";");
        return w;
    };

    // `var x: Unit = this.decode_impl(r);` is legal Scala but noisy and
    // trips -Wunused; emit the call as a bare statement instead.
    config.variable_decl_custom = [](Context_Statement_VARIABLE_DECL& vctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(type, vctx.get(vctx.var_decl.var_type));
        if (type.body.kind == ebm::TypeKind::ENCODER_RETURN || type.body.kind == ebm::TypeKind::DECODER_RETURN) {
            MAYBE(init, vctx.visit(vctx.var_decl.initial_value));
            return CODELINE(init.to_writer(), ";");
        }
        return pass;
    };
    config.byte_array_literal_wrapper = [](Context_Statement_VARIABLE_DECL&, std::string_view name, size_t length, const std::string& bytes) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        std::string elems;
        for (size_t i = 0; i < length; i++) {
            if (i) {
                elems += ", ";
            }
            unsigned char b = i < bytes.size() ? (unsigned char)bytes[i] : 0;
            elems += std::format("0x{:02x}.toByte", b);
        }
        return CODELINE("val ", name, " : Array[Byte] = Array[Byte](", elems, ");");
    };

    // Enum: object holding val constants (decode must accept undefined
    // values, so a Scala 3 enum is unsuitable -- its valueOf/fromOrdinal
    // reject unknown values).
    config.enum_decl_visitor = [](Context_Statement_ENUM_DECL& ectx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        auto name = ectx.identifier();
        std::string base = "Int";
        if (!is_nil(ectx.enum_decl.base_type)) {
            MAYBE(base_type, ectx.visit(ectx.enum_decl.base_type));
            base = base_type.to_string();
        }
        w.writeln("object ", name, " {");
        {
            auto scope = w.indent_scope();
            for (auto& member_ref : ectx.enum_decl.members.container) {
                MAYBE(member, ectx.get_field<"enum_member_decl">(member_ref));
                MAYBE(value_expr, ectx.visit(member.value));
                w.writeln("val ", ectx.identifier(member_ref), " : ", base, " = ", value_expr.to_writer(), ";");
            }
        }
        w.writeln("}");
        return w;
    };
    config.enum_member_decl_visitor = [](Context_Statement_ENUM_MEMBER_DECL&) -> expected<Result> {
        return Result{};
    };

    config.default_value_custom = [](Context_Expression_DEFAULT_VALUE& dctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(t, dctx.get(dctx.type));
        switch (t.body.kind) {
            case ebm::TypeKind::INT:
            case ebm::TypeKind::UINT:
            case ebm::TypeKind::USIZE:
            case ebm::TypeKind::FLOAT:
                return Result("0");
            case ebm::TypeKind::BOOL:
                return Result("false");
            case ebm::TypeKind::ENUM: {
                MAYBE(enum_names, first_enum_name(dctx, dctx.type));
                return CODE(enum_names.first, ".", enum_names.second);
            }
            case ebm::TypeKind::ARRAY:
            case ebm::TypeKind::VECTOR: {
                std::string len = "0";
                if (t.body.kind == ebm::TypeKind::ARRAY) {
                    if (auto l = t.body.length()) {
                        len = std::to_string(l->value());
                    }
                }
                MAYBE(elem, t.body.element_type());
                if (is_u8(dctx, elem)) {
                    return Result("new Array[Byte](" + len + ")");
                }
                MAYBE(elem_txt, dctx.visit(elem));
                return CODE("new Array[", elem_txt.to_writer(), "](", len, ")");
            }
            case ebm::TypeKind::STRUCT:
            case ebm::TypeKind::RECURSIVE_STRUCT: {
                MAYBE(typ, dctx.visit(dctx.type));
                return CODE("new ", typ.to_writer(), "()");
            }
            case ebm::TypeKind::OPTIONAL:
            case ebm::TypeKind::PTR:
            case ebm::TypeKind::VARIANT:
            case ebm::TypeKind::STRUCT_UNION:
                return Result("null");
            default:
                return pass;
        }
    };

    // Arrays
    config.array_size_visitor = [](Context_Expression_ARRAY_SIZE& actx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(arr, actx.visit(actx.array_expr));
        return CODE(arr.to_writer(), ".length");
    };
    config.append_visitor = [](Context_Statement_APPEND& actx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(target, actx.visit(actx.target));
        MAYBE(value, actx.visit(actx.value));
        return CODELINE(target.to_writer(), " = append(", target.to_writer(), ", ", value.to_writer(), ");");
    };
    // Scala indexes with (); the index must be Int. u8 elements (Byte) are
    // masked on read.
    config.index_access_custom = [](Context_Expression_INDEX_ACCESS& ictx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(base_str, ictx.visit(ictx.base));
        MAYBE(index_str, ictx.visit(ictx.index));
        if (scala_expr_is_u8_array(ictx, ictx.base)) {
            return CODE("((", base_str.to_writer(), ")((", index_str.to_writer(), ").toInt) & 0xFF)");
        }
        return CODE("(", base_str.to_writer(), ")((", index_str.to_writer(), ").toInt)");
    };
    // (a) Property stores route through the setter method (member_access_custom
    // would otherwise render the LHS as a getter call -- not an lvalue).
    // (b) The masked Array[Byte] read form is not an lvalue: emit the store
    // directly.
    config.assignment_custom = [](Context_Statement_ASSIGNMENT& actx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto prop_opt = actx.template get_field<"target.body.member.body.id.instance.body.property_decl">();
        if (prop_opt && !is_nil(prop_opt->setter_function.id)) {
            auto setter_ref = prop_opt->setter_function.id;
            auto fd_opt = actx.template get_field<"func_decl">(setter_ref);
            if (fd_opt && !is_nil(fd_opt->parent_format)) {
                MAYBE(base_ref, actx.template get_field<"target.body.base">());
                auto member_name = std::string(actx.identifier(setter_ref));
                std::string receiver;
                if (is_inner_anon_property(*prop_opt)) {
                    member_name = std::string(actx.identifier(prop_opt->parent_struct)) + "_" + member_name;
                    receiver = "this";  // hoisted onto parent_format
                }
                else {
                    MAYBE(base_str, actx.visit(base_ref));
                    receiver = base_str.to_string();
                }
                MAYBE(value_str, actx.visit(actx.value));
                CodeWriter w;
                w.write(receiver, ".", member_name, "(", value_str.to_writer());
                for (auto& p : fd_opt->params.container) {
                    auto is_state = actx.template get_field<"param_decl.is_state_variable">(p);
                    if (is_state && *is_state) {
                        w.write(", ", actx.identifier(p));
                    }
                }
                w.writeln(");");
                return w;
            }
        }
        auto target_expr = actx.get(actx.target);
        if (target_expr && target_expr->body.kind == ebm::ExpressionKind::INDEX_ACCESS) {
            auto base_ref = target_expr->body.base();
            auto index_ref = target_expr->body.index();
            if (base_ref && index_ref && scala_expr_is_u8_array(actx, *base_ref)) {
                MAYBE(base_str, actx.visit(*base_ref));
                MAYBE(index_str, actx.visit(*index_ref));
                MAYBE(value_str, actx.visit(actx.value));
                return CODELINE("(", base_str.to_writer(), ")((", index_str.to_writer(), ").toInt) = (", value_str.to_writer(), ").toByte;");
            }
            return pass;
        }
        return pass;
    };

    // u64 lives in a signed Long: shift/div/mod/compare need the unsigned
    // forms (`-1L >> 7` stays -1 forever -- the leb128 encode loop never
    // terminates with the arithmetic shift). Smaller uints are zero-extended
    // into wider signed types, so plain operators remain correct there.
    config.binary_op_custom = [](Context_Expression_BINARY_OP& bctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto left_expr = bctx.get(bctx.left);
        if (!left_expr) {
            return pass;
        }
        auto lt = bctx.get(left_expr->body.type);
        if (!lt || lt->body.kind != ebm::TypeKind::UINT) {
            return pass;
        }
        std::uint64_t bits = 0;
        if (auto sz = lt->body.size()) {
            bits = sz->value();
        }
        if (bits < 64) {
            return pass;
        }
        switch (bctx.bop) {
            case ebm::BinaryOp::right_shift:
            case ebm::BinaryOp::div:
            case ebm::BinaryOp::mod:
            case ebm::BinaryOp::less:
            case ebm::BinaryOp::less_or_eq:
            case ebm::BinaryOp::greater:
            case ebm::BinaryOp::greater_or_eq:
                break;
            default:
                return pass;
        }
        MAYBE(l, bctx.visit(bctx.left));
        MAYBE(r, bctx.visit(bctx.right));
        switch (bctx.bop) {
            case ebm::BinaryOp::right_shift:
                return CODE("(", l.to_writer(), " >>> ", r.to_writer(), ")");
            case ebm::BinaryOp::div:
                return CODE("java.lang.Long.divideUnsigned(", l.to_writer(), ", ", r.to_writer(), ")");
            case ebm::BinaryOp::mod:
                return CODE("java.lang.Long.remainderUnsigned(", l.to_writer(), ", ", r.to_writer(), ")");
            default:
                return CODE("(java.lang.Long.compareUnsigned(", l.to_writer(), ", ", r.to_writer(), ") ", to_string(bctx.bop), " 0)");
        }
    };

    // Casts: Scala uses .toInt/.toLong/... conversion methods instead of
    // C-style casts; masks/shifts mirror the ebm2java rules.
    config.type_cast_custom = [](Context_Expression_TYPE_CAST& tctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(target_t, tctx.get(tctx.type));
        MAYBE(src_t, tctx.get(tctx.type_cast_desc.from_type));
        if (auto lw = tctx.type_cast_desc.cast_call()) {
            MAYBE(call_expr, tctx.get(lw->id));
            if (get_id(call_expr.body.type) == get_id(tctx.type)) {
                return tctx.visit(lw->id);
            }
        }
        const auto src_expr_id = tctx.type_cast_desc.cast_call()
                                     ? tctx.type_cast_desc.cast_call()->id
                                     : tctx.type_cast_desc.source_expr;
        MAYBE(src, tctx.visit(src_expr_id));
        // Any-rendered source (VARIANT without common type / STRUCT_UNION)
        // into a concrete type: asInstanceOf (unboxes for value targets).
        if (scala_renders_any(tctx, tctx.type_cast_desc.from_type) && !scala_renders_any(tctx, tctx.type)) {
            MAYBE(type_str, tctx.visit(tctx.type));
            return CODE("(", src.to_writer(), ").asInstanceOf[", type_str.to_writer(), "]");
        }
        const auto tk = target_t.body.kind;
        const auto sk = src_t.body.kind;
        std::uint64_t target_bits = 0;
        if (auto sz = target_t.body.size()) {
            target_bits = sz->value();
        }
        if (tk == ebm::TypeKind::BOOL) {
            if (sk == ebm::TypeKind::BOOL) {
                return src;
            }
            return CODE("((", src.to_writer(), ") != 0)");
        }
        if (sk == ebm::TypeKind::BOOL) {
            return CODE("(if (", src.to_writer(), ") 1 else 0)");
        }
        if (tk == ebm::TypeKind::UINT) {
            if (target_bits == 0 || target_bits >= 64) {
                return CODE("(", src.to_writer(), ").toLong");
            }
            if (scala_uint_is_int(target_bits)) {
                std::uint32_t mask = (std::uint32_t)((1ull << target_bits) - 1);
                return CODE("((", src.to_writer(), ").toInt & 0x", std::format("{:X}", mask), ")");
            }
            std::uint64_t mask = (1ull << target_bits) - 1;
            return CODE("((", src.to_writer(), ").toLong & 0x", std::format("{:X}", mask), "L)");
        }
        if (tk == ebm::TypeKind::INT) {
            switch (target_bits) {
                case 8:
                    return CODE("(", src.to_writer(), ").toByte.toInt");
                case 16:
                    return CODE("(", src.to_writer(), ").toShort.toInt");
                case 32:
                    return CODE("(", src.to_writer(), ").toInt");
                case 0:
                case 64:
                    return CODE("(", src.to_writer(), ").toLong");
                default: {
                    auto shift = std::to_string(64 - target_bits);
                    if (scala_int_is_int(target_bits)) {
                        return CODE("((((", src.to_writer(), ").toLong << ", shift, ") >> ", shift, ")).toInt");
                    }
                    return CODE("(((", src.to_writer(), ").toLong << ", shift, ") >> ", shift, ")");
                }
            }
        }
        if (tk == ebm::TypeKind::USIZE) {
            return CODE("(", src.to_writer(), ").toLong");
        }
        if (tk == ebm::TypeKind::FLOAT) {
            return CODE("(", src.to_writer(), ").", target_bits <= 32 ? "toFloat" : "toDouble");
        }
        if (tk == ebm::TypeKind::ENUM) {
            // enums are their base integer type; casting into the enum's base
            // keeps the value representation.
            return src;
        }
        // arrays / structs / variants: representation is unchanged.
        return src;
    };

    // Scala has no ternary; `if` is an expression. Numeric branches must be
    // harmonized explicitly: Java's ?: unboxes/promotes (Integer vs int ->
    // int), but Scala infers a union type (`Integer | Int`) that conforms to
    // nothing useful. When the CONDITIONAL's own type is numeric, both
    // branches get the .toX conversion (unboxing Integer and widening Int in
    // one stroke). OPTIONAL/PTR-typed conditionals stay untouched: a null
    // branch must survive.
    config.conditional_visitor = [](Context_Expression_CONDITIONAL& cctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(cond_str, cctx.visit(cctx.condition));
        MAYBE(then_str, cctx.visit(cctx.then));
        MAYBE(else_str, cctx.visit(cctx.else_));
        std::string sfx;
        auto kind = ebm::TypeKind::META;
        std::uint64_t bits = 0;
        if (auto t = cctx.get(cctx.type)) {
            kind = t->body.kind;
            if (auto sz = t->body.size()) {
                bits = sz->value();
            }
            if (kind == ebm::TypeKind::VARIANT) {
                if (auto vd = t->body.variant_desc(); vd && !is_nil(vd->common_type)) {
                    if (auto ct = cctx.get(vd->common_type)) {
                        kind = ct->body.kind;
                        bits = 0;
                        if (auto sz = ct->body.size()) {
                            bits = sz->value();
                        }
                    }
                }
            }
        }
        switch (kind) {
            case ebm::TypeKind::UINT:
                sfx = scala_uint_is_int(bits) ? ".toInt" : ".toLong";
                break;
            case ebm::TypeKind::INT:
                sfx = scala_int_is_int(bits) ? ".toInt" : ".toLong";
                break;
            case ebm::TypeKind::USIZE:
                sfx = ".toLong";
                break;
            case ebm::TypeKind::FLOAT:
                sfx = bits <= 32 ? ".toFloat" : ".toDouble";
                break;
            default:
                break;
        }
        return CODE("(if (", cond_str.to_writer(), ") ((", then_str.to_writer(), ")", sfx, ") else ((", else_str.to_writer(), ")", sfx, "))");
    };

    // Scala has no break/continue. Loops containing BREAK/CONTINUE get a
    // try/catch scaffold around the ControlThrowable singletons thrown by
    // the Statement_BREAK/CONTINUE hooks:
    //
    //   try {                                  // if BREAK present
    //     while (cond) {
    //       try {                              // if CONTINUE present
    //         <body>
    //       } catch { case _: BgnContinueEx => () }
    //       <increment>
    //       <condition re-evaluation>
    //     }
    //   } catch { case _: BgnBreakEx => () }
    //
    // The nearest enclosing catch is the nearest enclosing loop, matching
    // EBM's unlabeled break/continue. The increment runs after the continue
    // catch, so CONTINUE keeps C `for`-loop semantics. Loops without
    // break/continue fall through to the default emission.
    config.loop_statement_custom = [](Context_Statement_LOOP_STATEMENT& lctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto& loop = lctx.loop;
        if (!is_nil(loop.lowered_statement.id)) {
            return pass;  // default visits the lowered form
        }
        const bool has_break = scala_has_ctrl(lctx, loop.body, ebm::StatementKind::BREAK);
        const bool has_continue = scala_has_ctrl(lctx, loop.body, ebm::StatementKind::CONTINUE);
        if (!has_break && !has_continue) {
            return pass;
        }
        CodeWriter w;
        if (auto init = loop.init(); init && !is_nil(*init)) {
            MAYBE(init_s, lctx.visit(*init));
            w.write(init_s.to_writer());
        }
        std::string cond = "true";
        CodeWriter condition_related;
        if (auto c = loop.condition()) {
            auto added = lctx.add_writer();
            MAYBE(expr, lctx.visit(c->cond));
            cond = expr.to_string();
            MAYBE(got, lctx.get_writer());
            condition_related = std::move(got.get());
            w.write(condition_related);
        }
        std::optional<decltype(w.indent_scope_ex())> break_scope;
        if (has_break) {
            w.writeln("try {");
            break_scope = w.indent_scope_ex();
        }
        w.writeln("while (", tidy_condition_brace(std::move(cond)), ") {");
        {
            auto loop_indent = w.indent_scope();
            {
                std::optional<decltype(w.indent_scope_ex())> cont_scope;
                if (has_continue) {
                    w.writeln("try {");
                    cont_scope = w.indent_scope_ex();
                }
                MAYBE(body, lctx.visit(loop.body));
                w.write(body.to_writer());
                if (cont_scope) {
                    cont_scope.reset();
                    w.writeln("} catch { case _: BgnContinueEx => () }");
                }
            }
            if (auto iter = loop.increment(); iter && !is_nil(*iter)) {
                MAYBE(step, lctx.visit(*iter));
                w.write(step.to_writer());
            }
            w.write(condition_related);
        }
        w.writeln("}");
        if (break_scope) {
            break_scope.reset();
            w.writeln("} catch { case _: BgnBreakEx => () }");
        }
        return w;
    };

    // Endian
    config.is_little_endian_visitor = [](Context_Expression_IS_LITTLE_ENDIAN& lctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (is_nil(lctx.endian_expr)) {
            return Result("(java.nio.ByteOrder.nativeOrder() == java.nio.ByteOrder.LITTLE_ENDIAN)");
        }
        auto var = lctx.identifier(lctx.endian_expr);
        return CODE(var, " == 1");
    };
    config.native_endian_check = "(java.nio.ByteOrder.nativeOrder() == java.nio.ByteOrder.LITTLE_ENDIAN)";
    config.little_endian_value = "1";

    // Stream helpers
    config.can_read_stream_visitor = [](Context_Expression_CAN_READ_STREAM& cctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto io_ = cctx.identifier(cctx.io_ref);
        MAYBE(size_str, get_size_str(cctx, cctx.num_bytes));
        return CODE("(", io_, ".remaining() >= (", size_str, "))");
    };
    config.get_remaining_bytes_custom = [](Context_Expression_GET_REMAINING_BYTES& gctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto io_ = gctx.identifier(gctx.io_ref);
        return CODE(io_, ".remaining()");
    };

    config.length_mismatch_wrapper = [](Context_Statement_LENGTH_CHECK& lctx, Result target, Result expected_len, std::string layer_str) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto escaped = futils::escape::escape_str<std::string>(layer_str);
        CodeWriter w;
        w.writeln("if ((", target.to_writer(), ").toLong != (", expected_len.to_writer(), ").toLong) {");
        w.indent_writeln("throw new BgnError(\"size mismatch when writing field ", escaped, ": expected \" + (", expected_len.to_writer(), ") + \" got \" + (", target.to_writer(), "));");
        w.writeln("}");
        return w;
    };

    // SUB_BYTE_RANGE: INPUT slices the next `length` bytes into a child
    // BgnInput; OUTPUT writes into a scratch BgnOutput, then splices into the
    // parent.
    config.sub_byte_range_wrapper = [](Context_Statement_SUB_BYTE_RANGE& sctx, std::string io_, std::string parent_io_, Result length_str, Result inner, bool track_offset) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        w.writeln("{");
        {
            auto s = w.indent_scope();
            w.writeln("val _sub_len: Long = (", length_str.to_writer(), ").toLong;");
            if (sctx.sub_byte_range.stream_type == ebm::StreamType::INPUT) {
                w.writeln("val ", io_, " : BgnInput = new BgnInput(", parent_io_, ".readBytes(_sub_len));");
                if (track_offset) {
                    w.writeln("val _rs_start: Long = runtime_state.offset;");
                }
                w.write(inner.to_writer());
                if (track_offset) {
                    w.writeln("runtime_state.offset = _rs_start + _sub_len;");
                }
            }
            else {
                w.writeln("val ", io_, " : BgnOutput = new BgnOutput();");
                if (track_offset) {
                    w.writeln("val _rs_start: Long = runtime_state.offset;");
                }
                w.write(inner.to_writer());
                w.writeln("if (", io_, ".offset.toLong != _sub_len) {");
                w.indent_writeln("throw new BgnError(\"sub-range size mismatch: expected \" + _sub_len + \" got \" + ", io_, ".offset);");
                w.writeln("}");
                w.writeln(parent_io_, ".writeBytes(", io_, ".buf, ", io_, ".offset.toLong);");
                if (track_offset) {
                    w.writeln("runtime_state.offset = _rs_start + _sub_len;");
                }
            }
        }
        w.writeln("}");
        return w;
    };

    // Byte-level READ_DATA / WRITE_DATA. Scalar reads/writes never reach the
    // backend un-lowered (ebmgen decomposes them into readBytes + shift
    // composition), so only the bytes IO wrappers are hooked.
    config.read_data_bytes_io_wrapper = [](Context_Statement_READ_DATA& rctx, BytesType, Result target, std::string io_) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (rctx.read_data.lowered_statement()) {
            return pass;
        }
        const bool track_offset = !rctx.read_data.attribute.is_peek();
        CodeWriter w;
        if (auto dyn = rctx.read_data.size.ref(); dyn && rctx.is(ebm::ExpressionKind::GET_REMAINING_BYTES, *dyn)) {
            w.writeln(target.to_writer(), " = ", io_, ".readRemaining();");
            if (track_offset) {
                ebmcodegen::util::append_runtime_offset(rctx, rctx.read_data.io_ref, w, CODE(target.to_writer(), ".length"));
            }
            return w;
        }
        MAYBE(size_str, get_size_str(rctx, rctx.read_data.size));
        w.writeln(target.to_writer(), " = ", io_, ".readBytes((", size_str, ").toLong);");
        if (track_offset) {
            ebmcodegen::util::append_runtime_offset(rctx, rctx.read_data.io_ref, w, CODE("(", size_str, ").toLong"));
        }
        return w;
    };
    config.write_data_bytes_io_wrapper = [](Context_Statement_WRITE_DATA& wctx, BytesType, Result target, std::string io_) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (wctx.write_data.lowered_statement()) {
            return pass;
        }
        MAYBE(size_str, get_size_str(wctx, wctx.write_data.size));
        CodeWriter w;
        w.writeln(io_, ".writeBytes(", target.to_writer(), ", (", size_str, ").toLong);");
        ebmcodegen::util::append_runtime_offset(wctx, wctx.write_data.io_ref, w, CODE("(", size_str, ").toLong"));
        return w;
    };

    // Property access `x.prop` -> getter method call; union storage access
    // `x.union_field.arm_field` -> asInstanceOf to the arm class.
    config.member_access_custom = [](Context_Expression_MEMBER_ACCESS& mctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        // `<receiver>.<getter>(<state args>)`; hoisted anon-inner accessors
        // live on parent_format, so their receiver is the outer instance,
        // not the variant-arm value the base points at.
        auto emit_getter_call = [&](std::string_view name, std::string_view state_args, bool on_outer) -> expected<Result> {
            CodeWriter call;
            if (on_outer) {
                call.write("this.", name, "(", state_args, ")");
                return Result(std::move(call));
            }
            MAYBE(base_str, mctx.visit(mctx.base));
            call.write(base_str.to_writer(), ".", name, "(", state_args, ")");
            return Result(std::move(call));
        };
        MAYBE(prop_info, analyze_property_member_access(mctx, mctx.member, false));
        if (prop_info) {
            if (!prop_info->getter || is_nil(prop_info->getter->parent_format)) {
                return pass;
            }
            auto name = prop_info->inner_anon
                            ? prop_info->hoisted_method_name("_")
                            : std::string(mctx.identifier(prop_info->getter_ref));
            return emit_getter_call(name, prop_info->getter_params.state_args, prop_info->inner_anon);
        }
        auto member_stmt = mctx.template get_field<"member.body.id.instance">();
        if (!member_stmt) {
            return pass;
        }
        if (member_stmt->body.kind == ebm::StatementKind::FUNCTION_DECL) {
            auto fd = member_stmt->body.func_decl();
            if (fd &&
                (fd->kind == ebm::FunctionKind::PROPERTY_GETTER || fd->kind == ebm::FunctionKind::COMPOSITE_GETTER) &&
                !is_nil(fd->parent_format)) {
                MAYBE(getter_params, collect_func_param_names(mctx, *fd));
                return emit_getter_call(mctx.identifier(member_stmt->id), getter_params.state_args, false);
            }
            return pass;
        }
        if (member_stmt->body.kind == ebm::StatementKind::FIELD_DECL) {
            // State variables are not fields (they arrive as parameters):
            // `this.header` must render as the same-named local `header`.
            if (auto fd = member_stmt->body.field_decl(); fd && fd->is_state_variable()) {
                MAYBE(member_ident, mctx.identifier(mctx.member));
                return Result(std::string(member_ident));
            }
            auto base_expr = mctx.get(mctx.base);
            if (!base_expr) {
                return pass;
            }
            auto base_type = mctx.get(base_expr->body.type);
            if (!base_type || base_type->body.kind != ebm::TypeKind::STRUCT_UNION) {
                return pass;
            }
            auto fd = member_stmt->body.field_decl();
            if (!fd) {
                return pass;
            }
            MAYBE(arm, get_identifier_layer_str(mctx, from_weak(fd->parent_struct), "_"));
            MAYBE(base_str, mctx.visit(mctx.base));
            MAYBE(member_ident, mctx.identifier(mctx.member));
            return CODE("(", base_str.to_writer(), ").asInstanceOf[", arm, "].", member_ident);
        }
        return pass;
    };

    // Union init checks: isInstanceOf against the expected arm class.
    config.init_check_visitor = [](Context_Statement_INIT_CHECK& ictx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ictx.init_check.init_check_type == ebm::InitCheckType::field_init_encode ||
            ictx.init_check.init_check_type == ebm::InitCheckType::field_init_decode) {
            return Result{};
        }
        MAYBE(field_txt, ictx.visit(ictx.init_check.target_field));
        MAYBE(expect_expr, ictx.get(ictx.init_check.expect_value));
        MAYBE(type_txt, ictx.visit(expect_expr.body.type));
        CodeWriter w;
        w.writeln("if (!((", field_txt.to_writer(), ").isInstanceOf[", type_txt.to_writer(), "])) {");
        {
            auto scope = w.indent_scope();
            if (ictx.init_check.init_check_type == ebm::InitCheckType::union_init_encode) {
                w.writeln("throw new BgnError(\"union not initialized for encoding\");");
            }
            else if (ictx.init_check.init_check_type == ebm::InitCheckType::union_get) {
                MAYBE(func_decl, ictx.get_field<"id.func_decl">(ictx.init_check.related_function));
                MAYBE(default_, as_DEFAULT_VALUE(ictx, func_decl.return_type));
                w.writeln("return ", default_.to_writer(), ";");
            }
            else {
                w.writeln(field_txt.to_writer(), " = new ", type_txt.to_writer(), "();");
            }
        }
        w.writeln("}");
        return w;
    };

    // Program: banner + outer object wrapping runtime and all declarations.
    // decl_toplevel carries variant-arm classes hoisted by field_decl_custom.
    config.program_decl_custom = [](Context_Statement_PROGRAM_DECL& pctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        write_generated_banner(pctx, w);
        w.writeln();
        w.writeln("object ", pctx.flags().object_name, " {");
        {
            auto scope = w.indent_scope();
            w.write_unformatted(scala_runtime_source());
            for (auto& stmt_ref : pctx.block.container) {
                MAYBE(d, pctx.visit(stmt_ref));
                for (auto& toplevel : pctx.config().decl_toplevel) {
                    w.writeln(toplevel);
                }
                pctx.config().decl_toplevel.clear();
                w.writeln(d.to_writer());
            }
        }
        w.writeln("}");
        return w;
    };

    return pass;
}

