/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry_class
  Available Variables:
    ctx: Context_entry
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(entry) {
    using namespace CODEGEN_NAMESPACE;
    auto& root = ctx.visitor.wm.root;
    MAYBE(entry_point, ctx.get_entry_point());
    MAYBE(result, ctx.visit(entry_point));
    return {};
}
