/*license*/
// Go のバックエンド。
//
//   ./nast2go -i input.bgn            標準出力へ
//   ./nast2go -i input.bgn -o out.go
//   ./nast2go -i input.bgn --unhandled error   未対応で止める
//
// 木を辿るのは共通側 (backend/entry.hpp)。ここに書くのは knob の設定だけ。
// 何も差し込まなければ全ノードが {{Unhandled node: ...}} として出るので、
// 出力を見ながら埋めていく。
//
// 今の段階: 型の宣言まで。encode/decode はまだ。
#include "../../backend/entry.hpp"

#include <format>

using namespace brgen::nast;
using namespace brgen::nast::backend;

struct GoConfig {
    static constexpr auto lang_name = "go";
    static constexpr auto file_extension = ".go";

    std::string_view package = "main";

    void bind(futils::cmdline::option::Context& ctx) {
        ctx.VarString<true>(&package, "package", "package name of the generated file", "NAME");
    }

    // Go は gofmt がタブ。桁の数え方も変わるので IndentStyle::tab() で揃える。
    IndentStyle indent_style() {
        return IndentStyle::tab();
    }
};

namespace {

    // Go の識別子は先頭が大文字なら公開。生成物は外から使うので上げる。
    std::string exported(std::string_view name) {
        if (name.empty()) {
            return std::string(name);
        }
        std::string out(name);
        out[0] = static_cast<char>(std::toupper(static_cast<unsigned char>(out[0])));
        return out;
    }

    template <class C>
    expected<std::string> type_name(C& c, Node<Type> t);

    // 配列の長さ。定数なら [N]T、そうでなければ []T にする。
    template <class C>
    std::optional<std::uint64_t> const_length(C& c, Node<Expr> len) {
        if (!len) {
            return std::nullopt;
        }
        // 定数畳み込みの結果は側の表にある。式を読み直さない。
        // (ConstantValue は evaluate の段が入れる)
        if (auto* v = c.tables().template table<ConstantValue>().get(len)) {
            if (v->kind == EvalKind::integer && !v->is_negative) {
                return v->integer;
            }
        }
        return std::nullopt;
    }

    template <class C>
    expected<std::string> type_name(C& c, Node<Type> t) {
        if (!t) {
            return unexpect_loc_error(t, "no type");
        }
        auto& a = c.arena();
        if (auto i = t.template as<IntType>()) {
            auto r = i.ref(a);
            // bit_size が 8/16/32/64 でないもの (u3 など) はまだ扱わない。
            auto bits = r->bit_size;
            if (bits != 8 && bits != 16 && bits != 32 && bits != 64) {
                return unexpect_loc_error(t, "int of {} bits does not map to a Go type yet", bits);
            }
            return std::format("{}int{}", r->is_signed ? "" : "u", bits);
        }
        if (auto f = t.template as<FloatType>()) {
            return std::format("float{}", f.ref(a)->bit_size);
        }
        if (t.template as<BoolType>()) {
            return std::string("bool");
        }
        if (auto arr = t.template as<ArrayType>()) {
            auto r = arr.ref(a);
            MAYBE(elem, type_name(c, r->element_type));
            if (auto n = const_length(c, r->length)) {
                return std::format("[{}]{}", *n, elem);
            }
            return std::format("[]{}", elem);
        }
        if (auto s = t.template as<StructType>()) {
            // 名前は元の宣言から取る。struct_type は宣言への弱い戻り辺。
            auto base = s.ref(a)->base;
            if (auto fmt = base.template as<Format>()) {
                return exported(ident_text(a, fmt.ref(a)->name));
            }
        }
        if (auto id = t.template as<IdentType>()) {
            return exported(ident_text(a, id.ref(a)->ident));
        }
        if (auto e = t.template as<EnumType>()) {
            return exported(ident_text(a, e.ref(a)->base.ref(a)->name));
        }
        return unexpect_loc_error(t, "no Go type for {}", to_string(t.type()));
    }

}  // namespace

NAST_BACKEND_ENTRY(GoConfig) {
    knobs.bind_Module(ctx, [](auto& c, Node<Module> n) -> expected<CodeWriter> {
        CodeWriter w;
        w.writeln("// Code generated by nast2go. DO NOT EDIT.");
        w.writeln(std::format("package {}", c.lang_config().package));
        for (auto& s : n.ref(c.arena())->statements) {
            MAYBE(part, c.visit(s));
            w.writeln();
            w.write(std::move(part));
        }
        return w;
    });

    knobs.bind_Format(ctx, [](auto& c, Node<Format> n) -> expected<CodeWriter> {
        auto& a = c.arena();
        auto r = n.ref(a);
        CodeWriter w;
        w.writeln(std::format("type {} struct {{", exported(ident_text(a, r->name))));
        {
            auto indent = w.indent_scope();
            for (auto& s : r->body.ref(a)->statements) {
                MAYBE(part, c.visit(s));
                w.write(std::move(part));
            }
        }
        w.writeln("}");
        return w;
    });

    knobs.bind_Field(ctx, [](auto& c, Node<Field> n) -> expected<CodeWriter> {
        auto& a = c.arena();
        auto r = n.ref(a);
        // 名前のないフィールド (アンカーやパディング) は構造体には出さない。
        auto name = ident_text(a, r->name);
        if (name.empty()) {
            return CodeWriter{};
        }
        MAYBE(type, type_name(c, r->type));
        CodeWriter w;
        w.writeln(std::format("{} {}", exported(name), type));
        return w;
    });

    return {};
}
