/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_TYPE_CAST_class
  Available Variables:
    ctx: Context_Expression_TYPE_CAST
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      type_cast_desc: const ebm::TypeCastDesc&
        source_expr: ExpressionRef
        from_type: TypeRef
        cast_kind: CastType
        cast_function: *WeakStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Expression_TYPE_CAST) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    return ctx.visit(ctx.type_cast_desc.source_expr);
}
