/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_SELF_class
  Available Variables:
    ctx: Context_Expression_SELF
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "layout.hpp"
DEFINE_VISITOR(Expression_SELF) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    InitialContext ictx{.visitor = ctx.visitor};

    MAYBE(_, analyze_layout(ictx, ctx.type))
    MAYBE(type_str, ctx.identifier(ctx.type));
    auto str = std::format("self<{}>", type_str);
    ctx.config().env.add_instruction({.op = ebm::OpCode::LOAD_SELF}, str);
    return Result{.str_repr = str};
}
