/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_IS_ERROR_class
  Available Variables:
    ctx: Context_Expression_IS_ERROR
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      target_expr: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Expression_IS_ERROR) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(target, ctx.visit(ctx.target_expr));
    ctx.config().env.add_instruction({.op = ebm::OpCode::IS_ERROR}, std::format("is_error({})", target.str_repr));
    return Result{.str_repr = std::format("is_error({})", target.str_repr)};
}
