/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_MATCH_STATEMENT_class
  Available Variables:
    ctx: Context_Statement_MATCH_STATEMENT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      match_statement: const ebm::MatchStatement&
        target: ExpressionRef
        is_exhaustive: bool
        reserved: std::uint8_t
        branches: Block
          len: Varint
          container: std::vector<StatementRef>
        lowered_if_statement: LoweredStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_MATCH_STATEMENT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    return ctx.visit(ctx.match_statement.lowered_if_statement.id);
}
