/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_FUNCTION_DECL_class
  Available Variables:
    ctx: Context_Statement_FUNCTION_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      func_decl: const ebm::FunctionDecl&
        name: IdentifierRef
        return_type: TypeRef
        params: Block
          len: Varint
          container: std::vector<StatementRef>
        parent_format: WeakStatementRef
        kind: FunctionKind
        property: *WeakStatementRef
        attribute: FunctionAttribute
          is_user_defined: bool
          has_wrapper: bool
          reserved: std::uint8_t
        wrapper_function: *StatementRef
        body: StatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_FUNCTION_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    for (auto& param : ctx.func_decl.params.container) {
        // Skip DECODER_INPUT/ENCODER_INPUT params — they are not passed
        // as arguments at runtime (Expression_CALL also skips them).
        auto kind = ctx.get_field<"param_decl.param_type.body.kind.optional">(param);
        if (kind == ebm::TypeKind::DECODER_INPUT || kind == ebm::TypeKind::ENCODER_INPUT) {
            continue;
        }
        ctx.config().env.add_param(param);
    }
    return ctx.visit(ctx.func_decl.body);
}
