/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_ARRAY_SIZE_class
  Available Variables:
    ctx: Context_Expression_ARRAY_SIZE
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      array_expr: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Expression_ARRAY_SIZE) {
    using namespace CODEGEN_NAMESPACE;
    MAYBE(array_type, ctx.get_field<"type.instance">(ctx.array_expr));
    if (array_type.body.kind == ebm::TypeKind::ARRAY) {
        MAYBE(size, array_type.body.length());
        return CODE(std::to_string(size.value()));
    }
    else if (array_type.body.kind == ebm::TypeKind::VECTOR) {
        MAYBE(array_expr_str, ctx.visit(ctx.array_expr));
        return CODE(array_expr_str.to_writer(), ".size");
    }
    return unexpect_error("Expression_ARRAY_SIZE: unsupported type kind {}", to_string(array_type.body.kind));
}
