/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_INIT_CHECK_class
  Available Variables:
    ctx: Context_Statement_INIT_CHECK
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      init_check: const ebm::InitCheck&
        init_check_type: InitCheckType
        target_field: ExpressionRef
        expect_value: ExpressionRef
        related_function: WeakStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include <ranges>
#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "ebmcodegen/stub/util.hpp"
DEFINE_VISITOR(Statement_INIT_CHECK) {
    using namespace CODEGEN_NAMESPACE;
    auto get_field_name = [&]() -> expected<std::string> {
        MAYBE(unwrapped, unwrap_index(ctx, ctx.init_check.target_field));
        auto field_ = ctx.get_field<"member.body.id">(unwrapped.index_layers.back());
        if (!field_) {
            field_ = ctx.get_field<"body.id">(unwrapped.index_layers.back());
            if (!field_) {
                return ebmgen::unexpect_error("failed to get target field");
            }
        }
        MAYBE(field, field_);
        MAYBE(field_name, get_identifier_layer_str(ctx, from_weak(field)));
        for (size_t i = 0; i < unwrapped.index.size(); ++i) {
            auto expr = unwrapped.index[unwrapped.index.size() - 1 - i];
            MAYBE(expr_txt, ctx.visit(expr));
            field_name += "[" + expr_txt.to_string() + "]";
        }
        return field_name;
    };
    if (ctx.init_check.init_check_type == ebm::InitCheckType::field_init_encode) {
        MAYBE(type, ctx.get_field<"body.type.instance">(ctx.init_check.target_field));
        if (type.body.kind == ebm::TypeKind::RECURSIVE_STRUCT) {
            MAYBE(target_txt, ctx.visit(ctx.init_check.target_field));
            CodeWriter w;
            w.writeln("if (!", target_txt.to_writer(), ") {");
            {
                auto scope = w.indent_scope();
                MAYBE(field_name, get_field_name());
                w.writeln("EBM_EMIT_ERROR(\"Field ", field_name, " not initialized\");");
                w.writeln("return -1;  /* field not initialized */");
            }
            w.writeln("}");
            return w;
        }
    }
    if (ctx.init_check.init_check_type == ebm::InitCheckType::field_init_decode) {
        MAYBE(type, ctx.get_field<"body.type.instance">(ctx.init_check.target_field));
        if (type.body.kind == ebm::TypeKind::RECURSIVE_STRUCT) {
            MAYBE(target_txt, ctx.visit(ctx.init_check.target_field));
            MAYBE(type_txt, ctx.visit(type.id));
            CodeWriter w;
            w.writeln("if (!", target_txt.to_writer(), ") {");
            {
                auto scope = w.indent_scope();
                auto without_ptr = type_txt.to_string();
                without_ptr = without_ptr.substr(0, without_ptr.size() - 4);  // remove _ptr
                w.writeln(type_txt.to_string(), " tmp = EBM_ALLOCATE(input,", without_ptr, ");");
                w.writeln("if (!tmp) {");
                {
                    auto scope2 = w.indent_scope();
                    MAYBE(field_name, get_field_name());
                    w.writeln("EBM_EMIT_ERROR(\"Field ", field_name, " not initialized; allocation failed\");");
                    w.writeln("return -1;  /* allocation failed */");
                }
                w.writeln("}");
                w.writeln(target_txt.to_writer(), " = tmp;");
            }
            w.writeln("}");
            return w;
        }
    }
    /*here to write the hook*/
    return "";
}
