#!/usr/bin/env python3
"""nodes.json から nodes.h を生成する。

各段の実装は gen/ にある。ここは読み込みと、出力の順番を決めるだけ。

  python src/core/nast/nodegen.py [-o <path>] [--schema <path>] [--check]
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from gen import Schema, Writer  # noqa: E402
from gen.access import emit_field_of, emit_fixed_string  # noqa: E402
from gen.arena import emit_arena  # noqa: E402
from gen.enums import (  # noqa: E402
    emit_enum_helper_decls,
    emit_enum_helpers,
    emit_enums,
    emit_expr_layers,
)
from gen.nodes import (  # noqa: E402
    emit_dispatch,
    emit_forward_decls,
    emit_get_node_type,
    emit_node,
    emit_node_data,
    emit_node_header,
    emit_node_type,
    emit_ref,
)
from gen.tables import emit_side_tables, emit_structs  # noqa: E402

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SCHEMA = os.path.join(SCRIPT_DIR, "nodes.json")
DEFAULT_OUT = os.path.join(SCRIPT_DIR, "nodes.h")

# ast_enum.h / deep_copy.h と同じ体裁
PROLOGUE = (
    "/*license*/\n"
    '// Code generated by "nodegen.py"; DO NOT EDIT.\n'
    "// edit nodes.json instead.\n"
    "#pragma once\n"
)


def generate(schema: Schema) -> str:
    """出力を組み立てる。

    C++ は前方参照が効かないので順番に意味がある。
    タグ型 -> NodeType -> enum ヘルパ -> Node/Ref -> 値型 -> NodeData ->
    フィールド名の対応表 -> 走査の入口 -> Arena -> side table。
    """
    includes = Writer()
    for inc in schema.includes:
        includes.write("#include ", inc, "\n")

    fwd = Writer()
    emit_forward_decls(fwd, schema)

    types = Writer()
    emit_enums(types, schema)
    emit_node_type(types, schema)
    # Node/Ref の field<"..."> が非型引数に取るので、Node より前に要る。
    emit_fixed_string(types)

    helpers = Writer()
    emit_enum_helper_decls(helpers)
    for enum in schema.enums:
        emit_enum_helpers(helpers, enum["name"], Schema.enum_members(enum))
    # NodeType にも出す。ツール側で全ノード種を走査したい場面があるため。
    emit_enum_helpers(helpers, "NodeType", [(n["name"], n["name"], []) for n in schema.nodes])

    layers = Writer()
    for enum in schema.enums:
        emit_expr_layers(layers, schema, enum)

    node_type_map = Writer()
    emit_get_node_type(node_type_map, schema)

    core = Writer()
    emit_node_header(core, schema)
    emit_node(core)
    emit_ref(core)

    values = Writer()
    emit_structs(values, schema)

    data = Writer()
    emit_node_data(data, schema)

    access = Writer()
    emit_field_of(access, schema)

    dispatch = Writer()
    emit_dispatch(dispatch, schema)

    arena = Writer()
    emit_arena(arena, schema)

    tables = Writer()
    emit_side_tables(tables, schema)

    out = Writer()
    out.write(PROLOGUE)
    out.write(includes.getvalue())
    out.write("namespace brgen::nast {\n")
    for part in (fwd, types, helpers, layers, node_type_map, core, values, data, access, dispatch,
                 arena, tables):
        out.write(part.getvalue())
    out.write("}\n")
    return out.getvalue()


def main() -> int:
    ap = argparse.ArgumentParser(description="generate nodes.h from nodes.json")
    ap.add_argument("--schema", default=DEFAULT_SCHEMA)
    ap.add_argument("-o", "--out", default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true",
                    help="書き込まず、既存の出力と一致するかだけ見る (CI 向け)")
    args = ap.parse_args()

    text = generate(Schema.load(args.schema))

    if args.check:
        if not os.path.exists(args.out):
            print(f"{args.out} does not exist", file=sys.stderr)
            return 1
        with open(args.out, encoding="utf-8") as f:
            if f.read() == text:
                return 0
        print(f"{args.out} is out of date; run nodegen.py", file=sys.stderr)
        return 1

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
