/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_LITERAL_INT64
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: ExpressionRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    type: TypeRef
    kind: ExpressionKind
    int64_value: std::uint64_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
// This code is included within the visit_Expression_LITERAL_INT64 function.
// We can use variables like `this` (for Visitor) and `int64_value` directly.
CodeWriter w;
w.write(std::to_string(int64_value));
return w;