/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: Expression_MEMBER_ACCESS_class
  Available Variables:
    ctx: Context_Expression_MEMBER_ACCESS
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      base: const ebm::ExpressionRef&
      member: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_MEMBER_ACCESS) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.config().member_access_custom) {
        CALL_OR_PASS(uniq, ctx.config().member_access_custom(ctx));
    }
    // Imported-module member access: `utf8.isUTF8` refers to a module-level decl that is
    // emitted into the output (the imported function is generated here), so drop the module
    // prefix and emit just the member. Language-independent, so it lives in the default
    // visitor (was previously ebm2rust-only; see E0425 / ebm2go `undefined: Utf8`).
    if (ctx.get_field<"base.body.id.import_decl">(ctx.item_id)) {
        MAYBE(member_only, ctx.identifier(ctx.member));
        CodeWriter wm;
        wm.write(member_only);
        return wm;
    }
    MAYBE(base_str, ctx.visit(ctx.base));
    MAYBE(ident, ctx.identifier(ctx.member));
    CodeWriter w;
    w.write(base_str.to_writer(), ".", ident);
    return w;
}
