/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_ADDRESS_OF_class
  Available Variables:
    ctx: Context_Expression_ADDRESS_OF
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      target_expr: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_ADDRESS_OF) {
    using namespace CODEGEN_NAMESPACE;
    MAYBE(target_expr, ctx.visit(ctx.target_expr));
    if (ctx.config().make_pointer_wrapper) {
        MAYBE(res, ctx.config().make_pointer_wrapper(target_expr));
        return res;
    }
    return target_expr;
}