/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: Expression_RANGE_EQUAL_class
  Available Variables:
    ctx: Context_Expression_RANGE_EQUAL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      lowered_expr: const ebm::LoweredExpressionRef&
        id: ExpressionRef
      range_expr: const ebm::ExpressionRef&
      value: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/


#include "../codegen.hpp"
DEFINE_VISITOR(Expression_RANGE_EQUAL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    // Default: emit the expanded form (a<=value && value<=b) stashed in lowered_expr.
    // Backends may override this hook to emit a native range check
    // (e.g. Rust `(a..=b).contains(&value)`); the lowered form is the fallback.
    return ctx.visit(ctx.lowered_expr.id);
}

