/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_RETURN_class
  Available Variables:
    ctx: Context_Statement_RETURN
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      related_function: const ebm::WeakStatementRef&
        id: StatementRef
      value: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include "../codegen.hpp"
DEFINE_VISITOR(Statement_RETURN) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.config().return_visitor) {
        return ctx.config().return_visitor(ctx);
    }
    /*here to write the hook*/
    CodeWriter w;

    if (!is_nil(ctx.value)) {
        auto add = ctx.add_writer();
        MAYBE(ret_val, ctx.visit(ctx.value));
        MAYBE(got, ctx.get_writer());
        w.merge(std::move(got.get()));
        w.writeln("return ", ret_val.to_writer(), ctx.config().endof_statement);
    }
    else {
        w.writeln("return", ctx.config().endof_statement);
    }

    return w;
}