/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ERROR_REPORT_class
  Available Variables:
    ctx: Context_Statement_ERROR_REPORT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      error_report: const ebm::ErrorReport&
        message: StringRef
        arguments: Expressions
          len: Varint
          container: std::vector<ExpressionRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_ERROR_REPORT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (ctx.config().error_report_visitor) {
        MAYBE(res, ctx.config().error_report_visitor(ctx));
        return res;
    }
    return ctx.get_impl<expected<Result>>([&](auto&& impl) {
        return impl.visitor_Statement_ERROR_REPORT_GeneratorDefaultHook.visit(ctx);
    });
}
