/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_METADATA
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    metadata: Metadata
      name: IdentifierRef
      values: Expressions
        len: Varint
        container: std::vector<ExpressionRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

CodeWriter w;
w.write(visitor.metadata_comment_prefix);
auto name = module_.get_associated_identifier(item_id);
w.write(" ", name);
if (metadata.values.container.size()) {
    w.write("(");
    bool first = true;
    for (auto& v : metadata.values.container) {
        if (!first) {
            w.write(", ");
        }
        first = false;
        MAYBE(val, visit_Expression(*this, v));
        w.write(val.to_writer());
    }
    w.write(")");
}
w.writeln(visitor.metadata_comment_suffix);
return w;