/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_ENCODER_RETURN_class
  Available Variables:
    ctx: Context_Type_ENCODER_RETURN
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::TypeRef
      kind: const ebm::TypeKind&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Type_ENCODER_RETURN) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    return ctx.config().encoder_return_type;
}
