/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_STRUCT_UNION_class
  Available Variables:
    ctx: Context_Type_STRUCT_UNION
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::TypeRef
      kind: const ebm::TypeKind&
      struct_union_desc: const ebm::StructUnionDesc&
        variant_desc: VariantDesc
          common_type: TypeRef
          members: Types
            len: Varint
            container: std::vector<TypeRef>
        related_field: WeakStatementRef
        lowered_match_statement: LoweredStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Type_STRUCT_UNION) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.config().struct_union_type_custom) {
        CALL_OR_PASS(result, ctx.config().struct_union_type_custom(ctx));
    }
    /*here to write the hook*/
    auto enum_name = ctx.config().variant_prefix + std::format("{}", get_id(ctx.item_id));
    return Result(enum_name);
}
