/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_META_class
  Available Variables:
    ctx: Context_Type_META
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::TypeRef
      kind: const ebm::TypeKind&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Type_META) {
    using namespace CODEGEN_NAMESPACE;
    if (!ctx.config().meta_type_name.empty()) {
        return Result(ctx.config().meta_type_name);
    }
    return ctx.get_impl<expected<Result>>([&](auto&& impl) {
        return impl.visitor_Type_META_GeneratorDefaultHook.visit(ctx);
    });
}
