/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Type_INT_class
  Available Variables:
    ctx: Context_Type_INT
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::TypeRef
      kind: const ebm::TypeKind&
      size: const ebm::Varint&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Type_INT) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    auto bit_size = ctx.size.value();
    if (ctx.config().make_int_type) {
        return ctx.config().make_int_type(bit_size);
    }
    if (!ctx.config().byte_aligned_int) {
        return CODE(ctx.config().int_prefix, std::to_string(bit_size), ctx.config().int_suffix);
    }
    if (bit_size <= 8) {
        return CODE(ctx.config().int_prefix, "8", ctx.config().int_suffix);
    }
    if (bit_size <= 16) {
        return CODE(ctx.config().int_prefix, "16", ctx.config().int_suffix);
    }
    if (bit_size <= 32) {
        return CODE(ctx.config().int_prefix, "32", ctx.config().int_suffix);
    }
    if (bit_size <= 64) {
        return CODE(ctx.config().int_prefix, "64", ctx.config().int_suffix);
    }
    return unexpect_error("unsupported integer size: {}", bit_size);
}
