import json
import subprocess
import sys
import pathlib


def generate_stub_headers(stub_dir: str):
    stub_names = [{
        "name": "asm/types.h",
        "content": """
typedef unsigned char __u8;
typedef unsigned short __u16;
typedef unsigned int __u32;
typedef unsigned long long __u64;
"""
    },"asm/posix_types.h"]
    for name in stub_names:
        name = name if isinstance(name, str) else name["name"]
        path = pathlib.Path(stub_dir) / name
        path.parent.mkdir(parents=True, exist_ok=True)
        wasExisting = path.exists()
        with open(path,"w",encoding="utf-8") as f:
            f.write("// Stub header generated by extract_enum.py\n")
            f.write("#pragma once\n")
            if isinstance(name, dict):
                f.write(name["content"])
        if not wasExisting:
            print(f"Generated stub header: {path}", file=sys.stderr)

def get_clang_ast_json(header_path: str):
    LINUX_ROOT = "save/linux"
    STUB_INCLUDE_PATH = pathlib.Path("save/linux/stub/").absolute()
    INCLUDE_PATH = pathlib.Path(f"{LINUX_ROOT}/include/").absolute()
    UAPI_HEADER = pathlib.Path(f"{LINUX_ROOT}/include/uapi/").absolute()
    HEADER_PATH = UAPI_HEADER / header_path
    generate_stub_headers(STUB_INCLUDE_PATH.as_posix())

    """Clangを使用してASTをJSONでダンプする"""
    cmd = [
        "clang", "-Xclang", "-ast-dump=json", 
        "-fsyntax-only", HEADER_PATH.as_posix(),
        "-I", UAPI_HEADER,"-I", INCLUDE_PATH,
        "-I", STUB_INCLUDE_PATH.as_posix()
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error: Clang failed with\n{result.stderr}", file=sys.stderr)
        if result.stdout == "":
            print("No output from Clang. Check if the header path is correct and if Clang is properly installed.", file=sys.stderr)
            return None
    return json.loads(result.stdout)

class EnumExtractor:
    def __init__(self):
        self.results = []
        self.member_to_enum = {}
        self.unnamed_count = 0

    

    def extract_enums(self,node):
        """ASTツリーを走査してEnum値を抽出する"""
        #print(node.get("kind"), node.get("name", ""))
        # enumの宣言（EnumDecl）を見つける
        if node.get("kind") == "EnumDecl":
            self.unnamed_count += 1
            enum_members = []
            # EnumDeclの子ノードにEnumConstantDeclがあるはず
            for child in node.get("inner", []):
                # Enumの各項目（EnumConstantDecl）を探す
                if child.get("kind") == "EnumConstantDecl":
                    name = child.get("name")
                    # valueは ConstantExpr -> IntegerLiteral の中にある
                    inner = child.get("inner", [])
                    found = False
                    for item in inner:
                        if "value" in item:
                            enum_members.append({
                                "name": name,
                                "value": int(item["value"])
                            })
                            found = True
                            break
                    if not found:
                        # 定数式がない場合は、前の値に1を加える（Cのenumのルール）
                        if len(enum_members) > 0:
                            enum_members.append({
                                "name": name,
                                "value": enum_members[-1]["value"] + 1
                            })
                        else:
                            enum_members.append({
                                "name": name,
                                "value": 0
                            })
                        self.member_to_enum[name] = node.get("name") or f"unnamed_enum_{self.unnamed_count}"
            #print(f"  Members: {enum_members}")
            self.results.append({
                "name": node.get("name") or f"unnamed_enum_{self.unnamed_count}",
                "members": enum_members
            })
        # 子ノードを再帰的に探索
        for child in node.get("inner", []):
            self.extract_enums(child)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python extract_enums.py <header.h>")
        sys.exit(1)

    ast = get_clang_ast_json(sys.argv[1])
    if ast:
        extractor = EnumExtractor()
        extractor.extract_enums(ast)
        # 結果をJSONで出力（または辞書として他の処理に渡す）
        with open("save/netlink_dsls/ast.json", "w", encoding="utf-8") as f:
            json.dump(extractor.results, f, indent=2)