/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_CONDITIONAL_class
  Available Variables:
    ctx: Context_Expression_CONDITIONAL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      condition: const ebm::ExpressionRef&
      else_: const ebm::ExpressionRef&
      lowered_expr: const ebm::LoweredExpressionRef&
        id: ExpressionRef
      then: const ebm::ExpressionRef&
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Expression_CONDITIONAL) {
    using namespace CODEGEN_NAMESPACE;
    MAYBE(cond_str, ctx.visit(ctx.condition));
    MAYBE(then_str, ctx.visit(ctx.then));
    MAYBE(else_str, ctx.visit(ctx.else_));

    return CODE("(", then_str.to_writer(), " if ", cond_str.to_writer(), " else ", else_str.to_writer(), ")");
}
