/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ERROR_REPORT
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    error_report: ErrorReport
      message: StringRef
      arguments: Expressions
        len: Varint
        container: std::vector<ExpressionRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
MAYBE(literal, module_.get_string_literal(error_report.message));
auto text = futils::escape::escape_str<std::string>(literal.body.data);
return std::format("raise Exception(\"{}\")", text);