/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: Visitor_before
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
std::map<std::uint64_t, std::string> multi_arg_property;