baseURL = 'https://on-keyday.github.io/brgen/doc'
languageCode = 'en-us'
title = 'Brgen Document'
publishDir = '../public/doc'

enableGitInfo = true

[param]
BookRepo = 'https://on-keyday.github.io/brgen/doc'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$','^RELEASE_TAG$']
