/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Expression_AS_ARG_before_class
  Available Variables:
    ctx: Context_Expression_AS_ARG_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      as_arg: const ebm::AsArgDesc&
        target_expr: ExpressionRef
        is_inout: bool
        reserved: std::uint8_t
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
#include "../codegen.hpp"
DEFINE_VISITOR(Expression_AS_ARG_before) {
    auto typ = ctx.get_kind(ctx.type);
    MAYBE(expr, ctx.get(ctx.as_arg.target_expr));
    // direct-decode mode: DECODER_INPUT は `<var>, <var>_off` を生成する (offset 引数自動付与)。
    // `<var>_off` は関数パラメータ/ SUB_BYTE_RANGE ローカルどちらでも `&mut usize` 型として存在するので
    // 自動 reborrow が効く。
    if (ctx.config().in_direct_decode && typ == ebm::TypeKind::DECODER_INPUT) {
        MAYBE(var, ctx.main_logic());
        return CODE(var.to_writer(), ", ", ebm2rust::offset_var(var.to_string()));
    }
    if (ctx.as_arg.is_inout()) {
        MAYBE(var, ctx.main_logic())
        return CODE("&mut ", var.to_writer());
    }
    if (typ == ebm::TypeKind::ENCODER_INPUT ||
        typ == ebm::TypeKind::DECODER_INPUT) {
        if (auto id = expr.body.id(); id && ctx.get_kind(*id) == ebm::StatementKind::VARIABLE_DECL) {
            MAYBE(var, ctx.main_logic())
            return CODE("&mut ", var.to_writer());
        }
    }
    return pass;
}