/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: includes
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/
#include <format>

namespace ebm2rust {
    enum class FunctionFlags : std::uint64_t {
        HasFillBuf = 1 << 0,
    };

    // Wrap an io-producing expression so `?` yields the structured Error type
    // with a location tag (bm2rust map_io_error analogue). `loc` is a field/
    // format layer path (see get_identifier_layer_str); it is embedded verbatim
    // as a Rust &'static str literal, so callers pass identifier-like strings.
    inline std::string map_io_err(bool is_decode, const std::string& loc, bool is_async = false) {
        return std::format("{}.map_err(|e| Error::{}(\"{}\", e))?",
                           is_async ? ".await" : "",
                           is_decode ? "DecodeError" : "EncodeError", loc);
    }

    constexpr bool add_flag(FunctionFlags& flags, FunctionFlags flag) {
        flags = static_cast<FunctionFlags>(static_cast<std::uint64_t>(flags) | static_cast<std::uint64_t>(flag));
        return true;
    }

    constexpr bool has_flag(FunctionFlags flags, FunctionFlags flag) {
        return (static_cast<std::uint64_t>(flags) & static_cast<std::uint64_t>(flag)) != 0;
    }

    // zero-copy direct-decode mode helpers. Offset は io 変数名から機械的に導出する
    // (Go 版 offset_var/offset_ref と同じ発想) ので config state を持たなくて済む。
    inline std::string offset_var(const std::string& io) {
        return io + "_off";
    }

    inline std::string offset_ref(const std::string& io) {
        return "*" + io + "_off";
    }

    // Emit `runtime_state.offset += (<size>) as usize;` when the stream is gated
    // (see ebmcodegen::util::has_absolute_offset). Per ADR 0008/0039 the increment
    // stays backend-side; the companion itself is threaded by lower_runtime_state.
    inline void append_runtime_offset(auto&& ctx, ebm::StatementRef io_ref, auto& w, auto&& size_expr) {
        if (ebmcodegen::util::has_absolute_offset(ctx, io_ref)) {
            w.writeln("runtime_state.offset += (", size_expr, ") as usize;");
        }
    }
}  // namespace ebm2rust