/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: Statement_INIT_CHECK_class
  Available Variables:
    ctx: Context_Statement_INIT_CHECK
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      init_check: const ebm::InitCheck&
        init_check_type: InitCheckType
        target_field: ExpressionRef
        expect_value: ExpressionRef
        related_function: WeakStatementRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_INIT_CHECK) {
    using namespace CODEGEN_NAMESPACE;
    if (ctx.init_check.init_check_type == ebm::InitCheckType::field_init_encode ||
        ctx.init_check.init_check_type == ebm::InitCheckType::field_init_decode) {
        return Result{};
    }
    MAYBE(target_expr, ctx.get(ctx.init_check.target_field));
    MAYBE(target_type, ctx.get(target_expr.body.type));
    MAYBE(expect_expr, ctx.get(ctx.init_check.expect_value));

    MAYBE(variant_index, get_struct_union_index(ctx, target_expr.body.type, expect_expr.body.type));

    MAYBE(target, ctx.visit(ctx.init_check.target_field));

    // Build variant name directly (not via type visit) so we don't inherit
    // lifetime annotations like `Variant30<'a>` that are invalid in
    // pattern/expression positions. The bare identifier works in all positions.
    auto enum_name = ctx.config().variant_prefix + std::format("{}", get_id(target_expr.body.type));
    auto alt = CODE(enum_name, "::V", std::to_string(variant_index));
    auto default_ = CODE(alt, "(Default::default())");

    bool is_mutable = (ctx.init_check.init_check_type == ebm::InitCheckType::union_init_decode ||
                       ctx.init_check.init_check_type == ebm::InitCheckType::union_set);
    ctx.config().variant_mutable_contexts[get_id(expect_expr.body.type)] = is_mutable;

    CodeWriter w;
    if (ctx.init_check.init_check_type == ebm::InitCheckType::union_init_encode) {
        w.writeln("if !matches!(", target.to_writer(), ", ", alt, "(_)) {");
        {
            auto scope = w.indent_scope();
            w.writeln("return Err(anyhow::anyhow!(\"unexpected value\"));");
        }
        w.writeln("}");
    }
    else if (ctx.init_check.init_check_type == ebm::InitCheckType::union_init_decode || ctx.init_check.init_check_type == ebm::InitCheckType::union_set) {
        w.writeln("if !matches!(", target.to_writer(), ", ", alt, "(_)) {");
        {
            auto scope = w.indent_scope();
            w.writeln(target.to_writer(), " = ", default_, ";");
        }
        w.writeln("}");
    }
    else if (ctx.init_check.init_check_type == ebm::InitCheckType::union_get) {
        w.writeln("if !matches!(", target.to_writer(), ", ", alt, "(_)) {");
        {
            auto scope = w.indent_scope();
            w.writeln("return None;");
        }
        w.writeln("}");
    }
    else {
        return unexpect_error("not supported init_check_type: {}", to_string(ctx.init_check.init_check_type));
    }

    return w;
}
