/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_LOOP_STATEMENT_before_class
  Available Variables:
    ctx: Context_Statement_LOOP_STATEMENT_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      loop: const ebm::LoopStatement&
        loop_type: LoopType
        collection: *ExpressionRef
        condition: *Condition
          cond: ExpressionRef
        increment: *StatementRef
        init: *StatementRef
        item_var: *StatementRef
        body: StatementRef
        lowered_statement: LoweredStatementRef
        next_lowered_loop: LoweredStatementRef
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Statement_LOOP_STATEMENT_before) {
    using namespace CODEGEN_NAMESPACE;
    // Only handle COUNTED (internal counter loop lowered from integer FOR_EACH).
    if (ctx.loop.loop_type != ebm::LoopType::COUNTED) {
        return pass;
    }

    MAYBE(item_var_ref, ctx.loop.item_var());
    MAYBE(collection_ref, ctx.loop.collection());

    // Get the counter type string for casting the limit expression to match.
    MAYBE(item_var_stmt, ctx.get(item_var_ref));
    MAYBE(var_decl_data, item_var_stmt.body.var_decl());
    MAYBE(counter_type_str, ctx.visit(var_decl_data.var_type));

    // Precompute the loop limit before any &mut borrow to avoid E0502.
    auto limit_var = std::string("__loop_limit_") + std::to_string(ctx.config().loop_limit_counter++);

    CodeWriter w;

    // Emit any side-effect statements from evaluating the limit expression.
    {
        auto add = ctx.add_writer();
        MAYBE(limit_expr, ctx.visit(collection_ref));
        MAYBE(got, ctx.get_writer());
        w.write(std::move(got.get()));
        // Cast limit to counter type to avoid type mismatch (e.g., u8 limit vs usize counter).
        w.writeln("let ", limit_var, " = (", tidy_condition_brace(limit_expr.to_string()), ") as ", counter_type_str.to_writer(), ";");
    }

    // Emit counter variable declaration: let mut __counter_N = 0;
    MAYBE(item_var_decl, ctx.visit(item_var_ref));
    w.write(item_var_decl.to_writer());

    // Get the counter variable name for the while condition and increment.
    auto counter_name = ctx.identifier(item_var_ref);

    // while counter < limit { body; counter += 1; }
    w.writeln("while ", counter_name, " < ", limit_var, " {");
    {
        auto scope = w.indent_scope();
        MAYBE(body, ctx.visit(ctx.loop.body));
        w.write(body.to_writer());
        w.writeln(counter_name, " += 1;");
    }
    w.writeln("}");

    return w;
}
