/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_ENUM_MEMBER_DECL
  Available variables:
    visitor: Visitor
    module_: MappingTable
    item_id: StatementRef
    generator_default_logic: std::function<expected<Result>()>
    default_logic: std::function<expected<Result>()>
    kind: StatementKind
    enum_member_decl: EnumMemberDecl
      name: IdentifierRef
      enum_decl: WeakStatementRef
      value: ExpressionRef
      string_repr: StringRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
auto ident = module_.get_identifier(enum_member_decl.name);
if (!ident) {
    return unexpect_error("identifier not found");
}
auto enum_ident = module_.get_associated_identifier(enum_member_decl.enum_decl);
MAYBE(enum_decl, module_.get_statement(enum_member_decl.enum_decl));
bool has_base = !is_nil(enum_decl.body.enum_decl()->base_type);
auto name = ident->body.data;

MAYBE(value_str, visit_Expression(*this, enum_member_decl.value));

return CODELINE("pub const ", name, ":Self = Self(", value_str.to_writer(), ");");
