/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Visitor_before
  Available variables:
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

/*here to write the hook*/
std::vector<CodeWriter> custom_types;
std::map<std::uint64_t, FunctionFlags> function_markers;
ebm::StatementRef current_function;
std::set<std::string> use_statements;