/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_FIELD_DECL_class
  Available Variables:
    ctx: Context_Statement_FIELD_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      field_decl: const ebm::FieldDecl&
        name: IdentifierRef
        field_type: TypeRef
        parent_struct: WeakStatementRef
        is_state_variable: bool
        inner_composite: bool
        has_metadata: bool
        reserved: std::uint8_t
        composite_field: *WeakStatementRef
        composite_getter: *LoweredStatementRef
        composite_setter: *LoweredStatementRef
        metadata: *Block
          len: Varint
          container: std::vector<StatementRef>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
DEFINE_VISITOR(Statement_FIELD_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    if (ctx.field_decl.is_state_variable()) {
        return {};
    }
    auto name = ctx.identifier();
    MAYBE(type, ctx.visit(ctx.field_decl.field_type));
    return CODELINE(type.to_writer(), " ", name, ";");
}
