/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: entry_before_class
  Available Variables:
    ctx: Context_entry_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/


#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "io_helpers.hpp"
DEFINE_VISITOR(entry_before) {
    using namespace CODEGEN_NAMESPACE;
    auto& config = ctx.config();

    // Ruby constants (class/module names) must start with an uppercase letter.
    // Override default `tmp` prefix so anonymous types/enums get a valid identifier.
    ctx.module().register_default_prefix(ebm::StatementKind::STRUCT_DECL, "Struct");
    ctx.module().register_default_prefix(ebm::StatementKind::ENUM_DECL, "Enum");

    // Block delimiters: Ruby uses `end` instead of braces.
    config.begin_block = "";
    config.end_block = "end";
    config.empty_block_marker = "";
    config.use_brace_for_condition = false;

    // Ruby uses `elsif` for else-if chains and a single closing `end`.
    config.use_elif = true;
    config.elif_keyword = "elsif";
    config.single_end_for_if_chain = true;

    // Statement terminator (Ruby uses newlines).
    config.endof_statement = "";
    config.endof_struct_definition = "";
    config.endof_enum_definition = "";
    config.enum_member_separator = "";

    // Class
    config.struct_keyword = "class";
    config.methods_inner_class = true;

    // No static typing
    config.variable_with_type = false;
    config.variable_define_keyword = "";
    config.immutable_variable_define_keyword = "";
    config.constant_define_keyword = "";
    config.forward_type_in_function_decl = false;
    config.function_return_type_separator = "";

    // Function
    config.function_define_keyword = "def";

    // Self
    config.self_value = "self";

    // Bool
    config.bool_type = "";
    config.bool_true = "true";
    config.bool_false = "false";
    config.void_type = "nil";

    // No int/uint/float type prefixes (Ruby is dynamically typed; types collapse to Integer/Float).
    config.int_prefix = "";
    config.int_suffix = "";
    config.uint_prefix = "";
    config.uint_suffix = "";
    config.float_prefix = "";
    config.float_suffix = "";
    config.usize_type_name = "Integer";

    config.make_int_type = [](size_t) -> expected<Result> { return Result("Integer"); };
    config.make_uint_type = [](size_t) -> expected<Result> { return Result("Integer"); };
    config.make_float_type = [](size_t) -> expected<Result> { return Result("Float"); };

    // Array operations
    config.array_size_get_function = "size";
    config.surrounded_array_size = false;  // arr.size
    config.append_function = "push";

    // Enum: emit as module + constants; access via `::`.
    config.enum_member_accessor = "::";

    // Comments
    config.metadata_comment_prefix = "#";
    config.metadata_comment_suffix = "";

    // Native endian check (Ruby).
    config.native_endian_check = "[1].pack(\"S\").bytes == [1, 0]";

    // Enums are emitted as Ruby modules (with constants), so `EnumName.new` is invalid.
    // Override default to plain `0`.
    config.default_value_custom = [](Context_Expression_DEFAULT_VALUE& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(type, ctx.get(ctx.type));
        if (type.body.kind == ebm::TypeKind::ENUM) {
            return Result("0");
        }
        return pass;
    };

    // Enums are modules (not callables), so `EnumName(value)` would invoke a method.
    // Casting an int to an enum is a no-op in Ruby — just return the source expression.
    config.type_cast_custom = [](Context_Expression_TYPE_CAST& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(target_type, ctx.get(ctx.type));
        if (target_type.body.kind == ebm::TypeKind::ENUM) {
            return ctx.visit(ctx.type_cast_desc.source_expr);
        }
        return pass;
    };

    // Default values
    config.default_value_option.pointer_init = "nil";
    config.default_value_option.optional_init = "nil";
    config.default_value_option.bytes_init = "[]";
    config.default_value_option.vector_init = "[]";
    config.default_value_option.encoder_return_init = "nil";
    config.default_value_option.decoder_return_init = "nil";
    config.default_value_option.object_init = ".new";  // Ruby: TypeName.new

    // Encoder/decoder I/O: pass-through (Ruby IO objects)
    config.encoder_return_type = "";
    config.decoder_return_type = "";
    config.encoder_input_type = "";
    config.decoder_input_type = "";

    // Parameters: emit just the name (Ruby has no static parameter types).
    config.param_visitor = [](Context_Statement_PARAMETER_DECL& ctx, Result /*type*/) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        return CODE(ctx.identifier());
    };

    // Field declarations: emit `attr_accessor :name`. State variables are skipped.
    // For union/variant fields, emit the variant member classes inline so
    // `is_a?(StructN)` references resolve.
    config.field_decl_visitor = [](Context_Statement_FIELD_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.field_decl.is_state_variable()) {
            return Result{};
        }
        MAYBE(struct_members, struct_union_members(ctx, ctx.field_decl.field_type));
        CodeWriter w;
        for (auto& m : struct_members) {
            w.write(m.second.to_writer());
        }
        w.writeln("attr_accessor :", ctx.identifier());
        return w;
    };

    // Function header: `def name(params)` only — no return type, no `->`.
    // Setters are prefixed with `set_` to avoid colliding with attr_accessor-generated `name=`.
    config.function_definition_start_wrapper = [](Result /*ret_type*/, std::string_view name, CodeWriter params, Context_Statement_FUNCTION_DECL& fctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        std::string func_name(name);
        if (is_setter_func(fctx.func_decl.kind)) {
            func_name = "set_" + func_name;
        }
        CodeWriter w;
        w.writeln("def ", func_name, "(", params, ")");
        return w;
    };

    // Enum: emit Ruby module with constants instead of `enum` keyword.
    config.enum_decl_visitor = [](Context_Statement_ENUM_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto name = ctx.identifier();
        CodeWriter w;
        w.writeln("module ", name);
        {
            auto scope = w.indent_scope();
            MAYBE(block, ctx.visit(ctx.enum_decl.members));
            w.write(block.to_writer());
        }
        w.writeln("end");
        return w;
    };

    // Skip `if IS_ERROR(...)` blocks: Ruby uses exception flow, not error checks.
    config.if_statement_custom = [](Context_Statement_IF_STATEMENT& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(cond_taken, ctx.get(ctx.if_statement.condition.cond));
        if (cond_taken.body.kind == ebm::ExpressionKind::IS_ERROR) {
            return Result{};
        }
        return pass;
    };

    // Stream offset: StringIO's `pos` attribute.
    config.get_stream_offset_custom = [](Context_Expression_GET_STREAM_OFFSET& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto io_ = ctx.identifier(ctx.io_ref);
        return CODE(io_, ".pos");
    };

    // Error report: raise Ruby exception.
    config.error_report_visitor = [](Context_Statement_ERROR_REPORT& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(literal, ctx.get(ctx.error_report.message));
        auto text = futils::escape::escape_str<std::string>(literal.body.data);
        return CODELINE("raise \"", text, "\"");
    };

    // Init check: Ruby `is_a?` for union/variant type guards.
    config.init_check_visitor = [](Context_Statement_INIT_CHECK& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.init_check.init_check_type == ebm::InitCheckType::field_init_encode ||
            ctx.init_check.init_check_type == ebm::InitCheckType::field_init_decode) {
            return Result{};
        }
        MAYBE(init_check_field, ctx.visit(ctx.init_check.target_field));
        MAYBE(expect_expr, ctx.get(ctx.init_check.expect_value));
        MAYBE(init_check_type, ctx.visit(expect_expr.body.type));
        CodeWriter w;
        if (ctx.init_check.init_check_type == ebm::InitCheckType::union_init_encode) {
            w.writeln("raise \"type mismatch: expected #{", init_check_type.to_writer(), "}, got #{", init_check_field.to_writer(), ".class}\" unless ", init_check_field.to_writer(), ".is_a?(", init_check_type.to_writer(), ")");
        }
        else {
            w.writeln("unless ", init_check_field.to_writer(), ".is_a?(", init_check_type.to_writer(), ")");
            {
                auto indent = w.indent_scope();
                if (ctx.init_check.init_check_type == ebm::InitCheckType::union_get) {
                    w.writeln("return nil");
                }
                else {
                    MAYBE(default_expr, ctx.visit(ctx.init_check.expect_value));
                    w.writeln(init_check_field.to_writer(), " = ", default_expr.to_writer());
                }
            }
            w.writeln("end");
        }
        return w;
    };

    // Program preamble: require 'stringio'.
    config.program_decl_custom = [](Context_Statement_PROGRAM_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        w.writeln("# Code generated by ebm2ruby at https://github.com/on-keyday/rebrgen");
        w.writeln("require 'stringio'");
        w.writeln();
        for (auto& stmt_ref : ctx.block.container) {
            MAYBE(d, ctx.visit(stmt_ref));
            w.writeln(d.to_writer());
        }
        return w;
    };

    // Read scalar: io.read(n).unpack1(fmt)
    config.read_data_custom = [](Context_Statement_READ_DATA& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.read_data.lowered_statement()) return pass;
        if (is_bytes_type(ctx, ctx.read_data.data_type)) return pass;
        MAYBE(target, ctx.visit(ctx.read_data.target));
        MAYBE(fmt, type_to_pack_format(ctx, ctx.read_data.data_type, ctx.read_data.attribute, ctx.read_data.size));
        MAYBE(size_str, get_size_str(ctx, ctx.read_data.size));
        auto io_ = ctx.identifier(ctx.read_data.io_ref);
        return CODELINE(target.to_writer(), " = ", io_, ".read(", size_str, ").unpack1(", fmt, ")");
    };

    // Read bytes array: io.read(n).bytes
    config.read_data_bytes_io_wrapper = [](Context_Statement_READ_DATA& ctx, BytesType /*cand*/, Result target, std::string io_) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.read_data.lowered_statement()) return pass;
        if (auto dyn = ctx.read_data.size.ref(); dyn && ctx.is(ebm::ExpressionKind::GET_REMAINING_BYTES, *dyn)) {
            return CODELINE(target.to_writer(), " = (", io_, ".read() || \"\").bytes");
        }
        MAYBE(size_str, get_size_str(ctx, ctx.read_data.size));
        return CODELINE(target.to_writer(), " = (", io_, ".read(", size_str, ") || \"\").bytes");
    };

    // Write scalar: io.write([v].pack(fmt))
    config.write_data_custom = [](Context_Statement_WRITE_DATA& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.write_data.lowered_statement()) return pass;
        if (is_bytes_type(ctx, ctx.write_data.data_type)) return pass;
        MAYBE(target, ctx.visit(ctx.write_data.target));
        MAYBE(fmt, type_to_pack_format(ctx, ctx.write_data.data_type, ctx.write_data.attribute, ctx.write_data.size));
        auto io_ = ctx.identifier(ctx.write_data.io_ref);
        return CODELINE(io_, ".write([", target.to_writer(), "].pack(", fmt, "))");
    };

    // Write bytes array: io.write(arr[0,n].pack("C*"))
    config.write_data_bytes_io_wrapper = [](Context_Statement_WRITE_DATA& ctx, BytesType /*cand*/, Result target, std::string io_) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.write_data.lowered_statement()) return pass;
        MAYBE(size_str, get_size_str(ctx, ctx.write_data.size));
        return CODELINE(io_, ".write(", target.to_writer(), "[0, ", size_str, "].pack(\"C*\"))");
    };

    // Sub-byte-range: Ruby StringIO slicing.
    config.sub_byte_range_visitor = [](Context_Statement_SUB_BYTE_RANGE& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto io_ = ctx.identifier(ctx.sub_byte_range.io_ref);
        MAYBE(do_io, ctx.visit(ctx.sub_byte_range.io_statement));
        CodeWriter w;
        auto parent_io_ = ctx.identifier(ctx.sub_byte_range.parent_io_ref);
        MAYBE(length, ctx.sub_byte_range.length());
        MAYBE(length_str, ctx.visit(length));
        if (ctx.sub_byte_range.stream_type == ebm::StreamType::INPUT) {
            w.writeln(io_, " = StringIO.new(", parent_io_, ".read(", length_str.to_writer(), ").b)");
        }
        else {
            w.writeln(io_, " = StringIO.new");
        }
        w.write(do_io.to_writer());
        if (ctx.sub_byte_range.stream_type == ebm::StreamType::OUTPUT) {
            w.writeln("raise \"length mismatch\" unless ", length_str.to_writer(), " == ", io_, ".string.bytesize");
            w.writeln(parent_io_, ".write(", io_, ".string)");
        }
        return w;
    };

    return pass;
}
