/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_READ_DATA_class
  Available Variables:
    ctx: Context_Statement_READ_DATA
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      read_data: const ebm::IOData&
        io_ref: StatementRef
        field: WeakStatementRef
        target: ExpressionRef
        data_type: TypeRef
        attribute: IOAttribute
          endian: Endian
          sign: bool
          is_peek: bool
          has_lowered_statement: bool
          has_offset: bool
          reserved: bool
          dynamic_ref: *StatementRef
        size: Size
          unit: SizeUnit
          ref: *ExpressionRef
          size: *Varint
        lowered_statement: *LoweredIOStatement
          lowering_type: LoweringIOType
          io_statement: LoweredStatementRef
        offset: *ExpressionRef
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include <string>
#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "ebmcodegen/stub/util.hpp"
DEFINE_VISITOR(Statement_READ_DATA) {
    using namespace CODEGEN_NAMESPACE;
    if (auto lowered = ctx.read_data.lowered_statement();
        lowered && lowered->lowering_type == ebm::LoweringIOType::VECTORIZED_IO) {
        return ctx.visit(lowered->io_statement.id);
    }
    auto is_bytes = is_bytes_type(ctx, ctx.read_data.data_type);
    if (!is_bytes) {
        if (auto lowered = ctx.read_data.lowered_statement()) {
            return ctx.visit(lowered->io_statement.id);
        }
    }
    if (is_bytes) {
        auto current_lvalue = ctx.config().is_lvalue;
        ctx.config().is_lvalue = true;
        MAYBE(target, ctx.visit(ctx.read_data.target));
        ctx.config().is_lvalue = current_lvalue;
        ebm::Instruction instr;
        instr.op = ebm::OpCode::READ_BYTES;
        ebm::OptionalImmediateSize imm;
        std::string str_repr;
        if (auto size = ctx.read_data.size.size()) {
            imm.is_immediate(true);
            imm.size(*size);
            str_repr = std::format("read_bytes({}, {})", target.str_repr, size->value());
        }
        else if (auto ref = ctx.read_data.size.ref()) {
            MAYBE(size_expr, ctx.visit(*ref));
            str_repr = std::format("read_bytes({}, {})", target.str_repr, size_expr.str_repr);
        }
        auto offset = ctx.read_data.attribute.has_offset() ? ctx.read_data.offset() : nullptr;
        if (offset) {
            auto value = ctx.get_field<"int_value">(*offset);
            if (!value) {
                return unexpect_error("Offset expression must be an integer literal");
            }
            instr.offset(*value);
        }
        instr.imm(imm);
        ctx.config().env.add_instruction(instr, str_repr);
        return Result{.str_repr = str_repr};
    }
    return ebmgen::unexpect_error("READ_DATA only supports byte array type in this implementation");
}
