/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/rebrgen
/*
  Name: Statement_VARIABLE_DECL_class
  Available Variables:
    ctx: Context_Statement_VARIABLE_DECL
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::StatementRef
      kind: const ebm::StatementKind&
      var_decl: const ebm::VariableDecl&
        name: IdentifierRef
        var_type: TypeRef
        initial_value: ExpressionRef
        decl_kind: VariableDeclKind
        is_reference: bool
        reserved: std::uint8_t
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
DEFINE_VISITOR(Statement_VARIABLE_DECL) {
    using namespace CODEGEN_NAMESPACE;
    /*here to write the hook*/
    MAYBE(initial_value, ctx.visit(ctx.var_decl.initial_value));
    auto identifier = ctx.identifier();
    ebm::Instruction instr;
    instr.op = ebm::OpCode::STORE_LOCAL;
    instr.reg(ebm::RegisterIndex{.index = ctx.item_id});
    ctx.config().env.add_instruction(instr, std::format("{} := {}", identifier, initial_value.str_repr));
    if (ctx.get_kind(ctx.var_decl.var_type) == ebm::TypeKind::DECODER_RETURN) {
        ctx.config().env.add_error_slot(ctx.item_id);
    }
    else {
        ctx.config().env.add_local(ctx.item_id);
    }
    return {};
}
