/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: entry_before_class
  Available Variables:
    ctx: Context_entry_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/

#include "../codegen.hpp"
#include "ebm/extended_binary_module.hpp"
#include "ebmcodegen/stub/dependency.hpp"
#include "ebmcodegen/stub/url.hpp"
#include "ebmcodegen/stub/util.hpp"

namespace CODEGEN_NAMESPACE {

    // Emit `runtime_state.offset += <size>;` when the stream is gated
    // (see ebmcodegen::util::has_absolute_offset). The increment stays
    // backend-side per ADR 0008/0039; the futils reader/writer cursor stays
    // view-local, the companion counts absolute bytes.
    inline void cpp_append_runtime_offset(auto& ctx, ebm::StatementRef io_ref, CodeWriter& w, auto&& size_expr) {
        if (ebmcodegen::util::has_absolute_offset(ctx, io_ref)) {
            w.writeln("runtime_state.offset += (", size_expr, ");");
        }
    }

}  // namespace CODEGEN_NAMESPACE

DEFINE_VISITOR(entry_before) {
    using namespace CODEGEN_NAMESPACE;
    using OutputPhase = std::remove_reference_t<decltype(ctx.config())>::OutputPhase;
    auto& config = ctx.config();

    // C++ type naming: std::uint8_t, std::int32_t, etc.
    config.int_prefix = "std::int";
    config.int_suffix = "_t";
    config.uint_prefix = "std::uint";
    config.uint_suffix = "_t";
    config.float_prefix = "";
    config.float_suffix = "";

    config.make_float_type = [](size_t bit_size) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (bit_size <= 32) {
            return CODE("float");
        }
        if (bit_size <= 64) {
            return CODE("double");
        }
        return unexpect_error("unsupported float size: {}", bit_size);
    };

    // C++ uses struct with methods inside
    config.methods_inner_class = true;
    config.struct_keyword = "struct";
    config.endof_struct_definition = ";";

    // Variable declarations: C++ uses type-first syntax
    config.variable_type_separator = " ";
    config.field_name_prior_to_type = false;
    config.variable_name_prior_to_type = false;
    config.parameter_name_prior_to_type = false;
    config.variable_with_type = true;
    config.variable_define_keyword = "";
    config.immutable_variable_define_keyword = "";
    config.constant_define_keyword = "constexpr";

    // Statement terminator
    config.endof_statement = ";";

    // C++ uses forward type in function declarations
    config.forward_type_in_function_decl = true;
    config.function_define_keyword = "";

    // self is (*this) for member functions
    config.self_value = "(*this)";

    // Enum settings
    config.enum_member_separator = ",";
    config.endof_enum_definition = ";";
    config.enum_member_accessor = "::";

    // Variant prefix
    config.variant_prefix = "Variant";

    // Use C++ function-style casts
    config.func_style_cast = true;

    // Size type
    config.usize_type_name = "size_t";

    // Array/vector size function: C++ uses .size()
    config.array_size_get_function = "size";

    // Append function (for std::vector)
    config.append_function = "push_back";

    // IO types - match json2cpp2's futils API
    config.encoder_return_type = "::futils::error::Error<>";
    config.decoder_return_type = "::futils::error::Error<>";
    config.encoder_input_type = "::futils::binary::writer&";
    config.decoder_input_type = "::futils::binary::reader&";

    // Default values
    config.default_value_option.encoder_return_init = "::futils::error::Error<>()";
    config.default_value_option.decoder_return_init = "::futils::error::Error<>()";
    config.default_value_option.pointer_init = "nullptr";
    config.default_value_option.optional_init = "std::nullopt";
    config.default_value_option.vector_init = "{}";
    config.default_value_option.bytes_init = "{}";

    // Property setter returns bool
    config.property_setter_return_type = "bool";
    config.setter_status_ok = "true";
    config.setter_status_failure = "false";

    // Native endian check
    config.native_endian_check = "(__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__)";

    // Bool type
    config.bool_type = "bool";
    config.bool_true = "true";
    config.bool_false = "false";

    // Array type wrapper: std::array<T, N>
    // For read/write temporaries, use actual arrays (not pointers) since
    // they're used for sub-byte IO buffer manipulation
    config.array_type_wrapper = [](Context_Type_ARRAY& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(elem_type, ctx.visit(ctx.element_type));
        auto len = ctx.length.value();
        return CODE("std::array<", elem_type.to_writer(), ", ", std::to_string(len), ">");
    };

    // Vector type wrapper: std::vector<T>
    config.vector_type_wrapper = [](Context_Type_VECTOR& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(elem_type, ctx.visit(ctx.element_type));
        return CODE("std::vector<", elem_type.to_writer(), ">");
    };

    // Optional type wrapper: std::optional<T>
    config.optional_type_wrapper = [](Result elem_type) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        return CODE("std::optional<", elem_type.to_writer(), ">");
    };

    // Pointer type wrapper: T* or std::optional<T>
    config.pointer_type_wrapper = [&](Result elem_type) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        return CODE(elem_type.to_writer(), "*");
    };

    // Recursive struct type wrapper: std::shared_ptr<T>
    config.recursive_struct_type_wrapper = [](Result elem_type) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        return CODE("std::shared_ptr<", elem_type.to_writer(), ">");
    };

    // Make pointer wrapper: &expr
    config.make_pointer_wrapper = [](Result elem) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        return CODE("(&", elem.to_writer(), ")");
    };

    // Make optional wrapper: std::optional(expr)
    config.make_optional_wrapper = [](Result elem) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        return CODE("std::make_optional(", elem.to_writer(), ")");
    };

    // Parameter type wrapper: state variables and the ADR 0039 RuntimeState
    // companion are INOUT, passed as reference
    config.param_type_wrapper = [](Context_Statement_PARAMETER_DECL& ctx, Result typ) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.param_decl.is_state_variable() || ctx.param_decl.is_runtime_state()) {
            return CODE(typ.to_writer(), "&");
        }
        return typ;
    };

    // Error handling hooks
    config.error_return_visitor = [](Context_Statement_ERROR_RETURN& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        // Propagate the original error value instead of replacing it with a generic message.
        if (!is_nil(ctx.value)) {
            MAYBE(val, ctx.visit(ctx.value));
            return CODELINE("return ", val.to_writer(), ";");
        }
        return CODELINE("return ::futils::error::Error<>(\"error\", ::futils::error::Category::lib);");
    };

    config.error_report_visitor = [](Context_Statement_ERROR_REPORT& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(literal, ctx.get(ctx.error_report.message));
        auto text = futils::escape::escape_str<std::string>(literal.body.data);
        return CODELINE(std::format("return ::futils::error::Error<>(\"{}\", ::futils::error::Category::lib);", text));
    };

    config.is_error_visitor = [](Context_Expression_IS_ERROR& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(t, ctx.visit(ctx.target_expr));
        return CODE(t.to_writer(), " != ::futils::error::Error<>()");
    };

    // Field declarations: add default initializers for C++
    config.field_decl_custom = [](Context_Statement_FIELD_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.field_decl.is_state_variable()) {
            return {};
        }
        // Note: struct_union_members(ctx, field_type) would here visit each
        // anon inner STRUCT_DECL and return their full `struct X {...};`
        // bodies for inline emission. We deliberately skip that — the
        // top-level sorted_struct loop emits each STRUCT_DECL once, and
        // nesting them again inside the parent class produces a duplicate
        // type whose unqualified name no longer resolves correctly in
        // out-of-class method bodies (e.g. holds_alternative<tmp667>
        // finding a different `tmp667` from a different scope).
        auto name = ctx.identifier();
        MAYBE(type, ctx.visit(ctx.field_decl.field_type));
        auto type_ref = ctx.field_decl.field_type;
        MAYBE(type_info, ctx.get(type_ref));
        std::string init;
        switch (type_info.body.kind) {
            case ebm::TypeKind::INT:
            case ebm::TypeKind::UINT:
            case ebm::TypeKind::FLOAT:
                init = " = 0";
                break;
            case ebm::TypeKind::BOOL:
                init = " = false";
                break;
            case ebm::TypeKind::ENUM:
                init = "{}";
                break;
            default:
                break;
        }
        return CODELINE(type.to_writer(), " ", name, init, ctx.config().endof_statement);
    };

    // Enum declaration: use enum class with base type
    config.enum_decl_visitor = [](Context_Statement_ENUM_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto name = ctx.identifier();
        CodeWriter w;
        if (is_nil(ctx.enum_decl.base_type)) {
            // No base type specified (e.g. state enums) — default to int
            w.writeln("enum class ", name, " : int {");
        }
        else {
            MAYBE(base_type, ctx.visit(ctx.enum_decl.base_type));
            w.writeln("enum class ", name, " : ", base_type.to_writer(), " {");
        }
        {
            auto scope = w.indent_scope();
            MAYBE(block, ctx.visit(ctx.enum_decl.members));
            w.write(block.to_writer());
        }
        w.writeln("};");
        return w;
    };

    // Don't use base type for field types (use enum class name directly)
    config.use_base_type_of_enum = false;

    // CAN_READ_STREAM: check if reader has at least num_bytes remaining
    config.can_read_stream_visitor = [](Context_Expression_CAN_READ_STREAM& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto io_ = ctx.identifier(ctx.io_ref);
        MAYBE(size_str, get_size_str(ctx, ctx.num_bytes));
        return CODE(io_, ".remain().size() >= ", size_str);
    };

    // GET_REMAINING_BYTES: number of bytes left in the reader
    config.get_remaining_bytes_custom = [](Context_Expression_GET_REMAINING_BYTES& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto io_ = ctx.identifier(ctx.io_ref);
        return CODE(io_, ".remain().size()");
    };

    // GET_STREAM_OFFSET: current byte offset in the stream
    // ADR 0039: GET_STREAM_OFFSET is emitted from lowered_expr (the RuntimeState
    // companion member access) by the default visitor. The futils reader's
    // `.offset()` is view-local and resets across sub-readers, so it cannot
    // express the absolute offset ADR 0038 requires.

    // SUB_BYTE_RANGE: create a sub-reader/writer over a byte range
    config.sub_byte_range_wrapper = [](Context_Statement_SUB_BYTE_RANGE& ctx, std::string io_, std::string parent_io_, Result length_str, Result do_io, bool track_offset) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        if (ctx.sub_byte_range.stream_type == ebm::StreamType::INPUT) {
            // Create sub-reader from parent reader's current position
            w.writeln("{");
            {
                auto scope = w.indent_scope();
                w.writeln("auto _sub_view = ", parent_io_, ".remain().substr(0, ", length_str.to_writer(), ");");
                w.writeln("::futils::binary::reader ", io_, "{_sub_view};");
                if (track_offset) {
                    w.writeln("const auto _rs_start = runtime_state.offset;");
                }
                w.write(do_io.to_writer());
                w.writeln(parent_io_, ".offset(", length_str.to_writer(), ");");
                if (track_offset) {
                    w.writeln("runtime_state.offset = _rs_start + (", length_str.to_writer(), ");");
                }
            }
            w.writeln("}");
        }
        else {
            // OUTPUT: write to a resizable temporary buffer then to parent
            w.writeln("{");
            {
                auto scope = w.indent_scope();
                w.writeln("std::string _sub_buf;");
                w.writeln("::futils::binary::writer ", io_, "{::futils::binary::resizable_buffer_writer<std::string>(), &_sub_buf, _sub_buf};");
                w.write(do_io.to_writer());
                w.writeln("if (!", parent_io_, ".write(_sub_buf)) {");
                {
                    auto scope2 = w.indent_scope();
                    w.writeln("return ::futils::error::Error<>(\"encode: sub_byte_range write failed\", ::futils::error::Category::lib);");
                }
                w.writeln("}");
            }
            w.writeln("}");
        }
        return w;
    };

    // INIT_CHECK: C++ unions don't have tags, so union_init checks are no-ops.
    // For recursive struct init, check for nullptr and allocate.
    config.init_check_visitor = [](Context_Statement_INIT_CHECK& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.init_check.init_check_type == ebm::InitCheckType::field_init_encode) {
            MAYBE(type, ctx.get_field<"body.type.instance">(ctx.init_check.target_field));
            if (type.body.kind == ebm::TypeKind::RECURSIVE_STRUCT) {
                MAYBE(target_txt, ctx.visit(ctx.init_check.target_field));
                CodeWriter w;
                w.writeln("if (!", target_txt.to_writer(), ") {");
                {
                    auto scope = w.indent_scope();
                    w.writeln("return ::futils::error::Error<>(\"field not initialized\", ::futils::error::Category::lib);");
                }
                w.writeln("}");
                return w;
            }
            return Result{};
        }
        if (ctx.init_check.init_check_type == ebm::InitCheckType::field_init_decode) {
            MAYBE(type, ctx.get_field<"body.type.instance">(ctx.init_check.target_field));
            if (type.body.kind == ebm::TypeKind::RECURSIVE_STRUCT) {
                MAYBE(target_txt, ctx.visit(ctx.init_check.target_field));
                MAYBE(type_txt, ctx.visit(type.id));
                CodeWriter w;
                w.writeln("if (!", target_txt.to_writer(), ") {");
                {
                    auto scope = w.indent_scope();
                    w.writeln(target_txt.to_writer(), " = std::make_shared<", type_txt.to_writer(), ">();");
                }
                w.writeln("}");
                return w;
            }
            return Result{};
        }
        // For std::variant-based unions:
        // union_init_encode: check that the variant holds the expected type
        // union_init_decode/union_set: assign default value if not already the right type
        // union_get: return nullopt if not the right type
        MAYBE(target_expr, ctx.get(ctx.init_check.target_field));
        MAYBE(expect_expr, ctx.get(ctx.init_check.expect_value));
        MAYBE(expect_type, ctx.visit(expect_expr.body.type));

        MAYBE(target, ctx.visit(ctx.init_check.target_field));

        CodeWriter w;
        if (ctx.init_check.init_check_type == ebm::InitCheckType::union_init_encode) {
            w.writeln("if (!std::holds_alternative<", expect_type.to_writer(), ">(", target.to_writer(), ")) {");
            {
                auto scope = w.indent_scope();
                w.writeln("return ::futils::error::Error<>(\"unexpected variant type\", ::futils::error::Category::lib);");
            }
            w.writeln("}");
        }
        else if (ctx.init_check.init_check_type == ebm::InitCheckType::union_init_decode ||
                 ctx.init_check.init_check_type == ebm::InitCheckType::union_set) {
            w.writeln("if (!std::holds_alternative<", expect_type.to_writer(), ">(", target.to_writer(), ")) {");
            {
                auto scope = w.indent_scope();
                w.writeln(target.to_writer(), " = ", expect_type.to_writer(), "{};");
            }
            w.writeln("}");
        }
        else if (ctx.init_check.init_check_type == ebm::InitCheckType::union_get) {
            w.writeln("if (!std::holds_alternative<", expect_type.to_writer(), ">(", target.to_writer(), ")) {");
            {
                auto scope = w.indent_scope();
                MAYBE(kind, ctx.get_field<"func_decl.return_type.kind">(ctx.init_check.related_function));
                if (kind == ebm::TypeKind::OPTIONAL) {
                    w.writeln("return std::nullopt;");
                }
                else {
                    w.writeln("return nullptr;");
                }
            }
            w.writeln("}");
        }
        return w;
    };

    // Variant type: use common_type if available, otherwise std::variant
    config.variant_type_custom = [](Context_Type_VARIANT& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (!is_nil(ctx.variant_desc.common_type)) {
            return ctx.visit(ctx.variant_desc.common_type);
        }
        // Build std::variant<std::monostate, T1, T2, ...>
        // std::monostate is prepended so the variant is always default-constructible,
        // regardless of whether the first alternative is. Access is type-based
        // (std::holds_alternative<T> / std::get<T>), so the index shift is harmless.
        CodeWriter w;
        w.write("std::variant<std::monostate");
        for (auto& m : ctx.variant_desc.members.container) {
            w.write(", ");
            MAYBE(type, ctx.visit(m));
            w.write(type.to_writer());
        }
        w.write(">");
        return Result(std::move(w));
    };

    // Struct union type: emit inner struct definitions, then generate std::variant
    // Assignment whose target is a MEMBER_ACCESS to a PROPERTY cannot use
    // the default `target = value` form because the getter returns
    // `const T*` and dereferencing it isn't writable. Call the overloaded
    // setter method instead. Applies the same prefix rule as the read path.
    config.assignment_custom = [](Context_Statement_ASSIGNMENT& actx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(target_expr, actx.get(actx.target));
        if (target_expr.body.kind != ebm::ExpressionKind::MEMBER_ACCESS) {
            return pass;
        }
        auto base_p = target_expr.body.base();
        auto member_p = target_expr.body.member();
        if (!base_p || !member_p) {
            return pass;
        }
        MAYBE(member_expr, actx.get(*member_p));
        auto id_p = member_expr.body.id();
        if (!id_p) {
            return pass;
        }
        MAYBE(referent, actx.get(from_weak(*id_p)));
        if (referent.body.kind != ebm::StatementKind::PROPERTY_DECL) {
            return pass;
        }
        auto prop_p = referent.body.property_decl();
        if (!prop_p) {
            return pass;
        }
        MAYBE(member_ident, actx.identifier(*member_p));
        MAYBE(value_w, actx.visit(actx.value));
        std::string method_name(member_ident);
        std::string base_text;
        if (is_inner_anon_property(*prop_p)) {
            auto inner_name = actx.identifier(prop_p->parent_struct);
            method_name = std::string(inner_name) + "_" + method_name;
            base_text = "(*this)";
        }
        else {
            MAYBE(base_w, actx.visit(*base_p));
            base_text = base_w.to_string();
        }
        return CODELINE(base_text, ".", method_name, "(", value_w.to_writer(), ")", actx.config().endof_statement);
    };
    // `Uint64(variant)` is invalid C++; emit `std::get<Uint64>(variant)`
    // for casts that extract a member out of a pure VARIANT type.
    // (Casts in the opposite direction — member -> variant — work via
    // std::variant's implicit converting constructor.)
    config.type_cast_custom = [](Context_Expression_TYPE_CAST& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto from_type = ctx.type_cast_desc.from_type;
        if (is_nil(from_type)) {
            return pass;
        }
        MAYBE(from_type_full, ctx.get(from_type));
        if (from_type_full.body.kind != ebm::TypeKind::VARIANT) {
            return pass;
        }
        auto vd = from_type_full.body.variant_desc();
        if (!vd || !is_nil(vd->common_type)) {
            return pass;
        }
        for (auto& m : vd->members.container) {
            if (get_id(m) == get_id(ctx.type)) {
                MAYBE(source, ctx.visit(ctx.type_cast_desc.source_expr));
                MAYBE(target_type_str, ctx.visit(ctx.type));
                return CODE("std::get<", target_type_str.to_writer(), ">(", source.to_writer(), ")");
            }
        }
        return pass;
    };
    config.struct_union_type_custom = [](Context_Type_STRUCT_UNION& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        // Emit struct definitions for each member type as toplevel

        // Build std::variant<std::monostate, T1, T2, ...>
        // See variant_type_custom above for the rationale.
        CodeWriter w;
        w.write("std::variant<std::monostate");
        for (auto& m : ctx.struct_union_desc.variant_desc.members.container) {
            w.write(", ");
            MAYBE(type, ctx.visit(m));
            w.write(type.to_writer());
        }
        w.write(">");
        return Result(std::move(w));
    };

    // Program declaration: forward reference resolution with sorted struct output
    config.program_decl_custom = [](Context_Statement_PROGRAM_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;

        // Phase 0: Header prologue
        write_generated_banner(ctx, w);
        w.writeln("#pragma once");
        w.writeln("#include <cstdint>");
        w.writeln("#include <cstddef>");
        w.writeln("#include <vector>");
        w.writeln("#include <array>");
        w.writeln("#include <optional>");
        w.writeln("#include <variant>");
        w.writeln("#include <memory>");
        w.writeln("#include <string>");
        w.writeln("");
        w.writeln("#include <binary/flags.h>");
        w.writeln("#include <binary/float.h>");
        w.writeln("#include <view/iovec.h>");
        w.writeln("#include <binary/number.h>");
        w.writeln("#include <error/error.h>");
        w.writeln("");

        // Phase 1: Enum definitions + top-level constants + struct forward declarations
        for (const auto& stmt : ctx.module().module().statements) {
            auto enum_decl = stmt.body.enum_decl();
            if (enum_decl) {
                MAYBE(enum_code, ctx.visit(stmt));
                w.writeln(enum_code.to_writer());
            }
        }
        w.writeln("");

        // Top-level CONSTANT variable declarations (e.g. AF_INET ::= u16(2))
        // Walk all statements globally because constants may live in imported modules' PROGRAM_DECLs.
        for (const auto& stmt : ctx.module().module().statements) {
            auto var_decl = stmt.body.var_decl();
            if (!var_decl || var_decl->decl_kind() != ebm::VariableDeclKind::CONSTANT) {
                continue;
            }
            MAYBE(var_code, ctx.visit(stmt.id));
            w.writeln(var_code.to_writer());
        }
        w.writeln("");

        MAYBE(sorted, sorted_struct(ctx));
        for (auto& stmt_ref : sorted) {
            auto name = ctx.identifier(stmt_ref);
            w.writeln("struct ", name, ";");
        }
        w.writeln("");

        // Phase 2: Struct definitions with method signatures only (no bodies)
        ctx.config().output_phase = OutputPhase::DeclarationOnly;
        for (auto& stmt_ref : sorted) {
            MAYBE(struct_code, ctx.visit(stmt_ref));
            for (auto& toplevel : ctx.config().decl_toplevel) {
                w.writeln(toplevel);
            }
            ctx.config().decl_toplevel.clear();
            w.writeln(struct_code.to_writer());
        }
        w.writeln("");

        // Phase 3: Out-of-class method definitions (full bodies)
        ctx.config().output_phase = OutputPhase::FunctionBodyOnly;
        for (auto& stmt_ref : sorted) {
            MAYBE(func_code, ctx.visit(stmt_ref));
            auto code = func_code.to_writer();
            if (!code.empty()) {
                w.write(code);
                w.writeln("");
            }
        }

        ctx.config().output_phase = OutputPhase::Normal;
        return w;
    };

    // Read data: use futils binary read API
    config.read_data_bytes_io_wrapper = [](Context_Statement_READ_DATA& ctx, BytesType cand, Result target, std::string io_name) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.read_data.lowered_statement()) {
            return pass;
        }
        MAYBE(size_str, get_size_str(ctx, ctx.read_data.size));
        const bool track_offset = !ctx.read_data.attribute.is_peek();
        CodeWriter w;
        if (cand == BytesType::array) {
            // Read only size_str bytes; the backing std::array may be larger (e.g. alignment padding).
            w.writeln("if (!", io_name, ".read(::futils::view::wvec(", target.to_writer(), ".data(), ", size_str, "))) {");
            {
                auto scope = w.indent_scope();
                MAYBE(layer_str, get_identifier_layer_str(ctx, from_weak(ctx.read_data.field)));
                w.writeln(std::format("return ::futils::error::Error<>(\"decode: {}: read byte array failed\", ::futils::error::Category::lib);", layer_str));
            }
            w.writeln("}");
            if (track_offset) {
                cpp_append_runtime_offset(ctx, ctx.read_data.io_ref, w, size_str);
            }
        }
        else {
            // Vector<uint8_t> - resize then read
            w.writeln("{");
            {
                auto scope = w.indent_scope();
                w.writeln("auto _sz = ", size_str, ";");
                w.writeln(target.to_writer(), ".resize(_sz);");
                w.writeln("if (!", io_name, ".read(", target.to_writer(), ")) {");
                {
                    auto scope2 = w.indent_scope();
                    MAYBE(layer_str, get_identifier_layer_str(ctx, from_weak(ctx.read_data.field)));
                    w.writeln(std::format("return ::futils::error::Error<>(\"decode: {}: read bytes failed\", ::futils::error::Category::lib);", layer_str));
                }
                w.writeln("}");
                if (track_offset) {
                    cpp_append_runtime_offset(ctx, ctx.read_data.io_ref, w, "_sz");
                }
            }
            w.writeln("}");
        }
        return w;
    };

    // Write data bytes
    config.write_data_bytes_io_wrapper = [](Context_Statement_WRITE_DATA& ctx, BytesType cand, Result target, std::string io_name) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        if (ctx.write_data.lowered_statement()) {
            return pass;
        }
        MAYBE(size_str, get_size_str(ctx, ctx.write_data.size));
        CodeWriter w;
        if (cand == BytesType::array) {
            // For fixed-size array, write only the first size_str bytes (not the entire array)
            // because sub-byte IO buffers may be larger than the actual write size (e.g. QUIC varint).
            w.writeln("if (!", io_name, ".write(::futils::view::rvec(", target.to_writer(), ".data(), ", size_str, "))) {");
        }
        else {
            w.writeln("if (!", io_name, ".write(", target.to_writer(), ")) {");
        }
        {
            auto scope = w.indent_scope();
            MAYBE(layer_str, get_identifier_layer_str(ctx, from_weak(ctx.write_data.field)));
            w.writeln(std::format("return ::futils::error::Error<>(\"encode: {}: write failed\", ::futils::error::Category::lib);", layer_str));
        }
        w.writeln("}");
        cpp_append_runtime_offset(ctx, ctx.write_data.io_ref, w, size_str);
        return w;
    };

    // Struct declaration: phase-aware
    config.struct_definition_start_wrapper = [](Context_Statement_STRUCT_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto name = ctx.identifier();
        CodeWriter w;
        if (ctx.config().output_phase == OutputPhase::Normal) {
            // Normal mode: emit forward declaration + definition
            w.writeln("struct ", name, ";");
        }
        // DeclarationOnly or Normal: start struct definition
        w.writeln("struct ", name, " {");
        return w;
    };

    // Struct emission with anon-inner-property hoisting. Property accessors
    // belonging to anon inner structs are declared on (and defined as
    // methods of) the outer parent_format class; their own struct body
    // skips them. See entry_before_class function_decl_custom for the
    // matching method-name prefixing.
    config.struct_decl_custom = [](Context_Statement_STRUCT_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        using Phase = std::remove_reference_t<decltype(ctx.config())>::OutputPhase;
        const auto phase = ctx.config().output_phase;
        if (phase == Phase::Normal) {
            return pass;  // Normal phase is not used during program emission
        }
        const bool is_anon_inner = is_nil(ctx.struct_decl.name);

        if (phase == Phase::FunctionBodyOnly) {
            // Phase 3: out-of-class method definitions.
            CodeWriter w;
            if (is_anon_inner) {
                // Anon inner: only its own codec / user methods, no
                // property accessor definitions (those are emitted from
                // the outer parent_format struct).
                MAYBE_VOID(_c, ebmcodegen::util::emit_struct_codec(ctx, w));
                MAYBE_VOID(_m, ebmcodegen::util::emit_struct_user_methods(ctx, w));
                return w;
            }
            MAYBE_VOID(_self, ebmcodegen::util::emit_struct_methods(ctx, w));
            std::vector<ebm::WeakStatementRef> descendants;
            std::unordered_set<std::uint64_t> seen;
            ebm::WeakStatementRef self_weak{};
            self_weak.id = ctx.item_id;
            MAYBE_VOID(_collect, ebmcodegen::util::collect_anon_inner_descendants(ctx, self_weak, descendants, seen));
            for (auto& inner_ref : descendants) {
                MAYBE(inner_stmt, ctx.get(from_weak(inner_ref)));
                auto inner_decl_p = inner_stmt.body.struct_decl();
                if (!inner_decl_p || !inner_decl_p->has_properties()) {
                    continue;
                }
                auto inner_props = inner_decl_p->properties();
                if (!inner_props) {
                    continue;
                }
                for (auto& prop_ref : inner_props->container) {
                    MAYBE(prop_w, ctx.visit(prop_ref));
                    w.writeln(prop_w.to_writer());
                }
            }
            return w;
        }

        // Phase 2 (DeclarationOnly): build struct body inline so we can
        // skip / aggregate property accessors per the anon-inner rule.
        CodeWriter w;
        if (ctx.config().struct_definition_start_wrapper) {
            MAYBE(start, ctx.config().struct_definition_start_wrapper(ctx));
            w.write(start.to_writer());
        }
        else {
            auto name = ctx.identifier();
            w.writeln(ctx.config().struct_keyword, " ", name, " ", ctx.config().begin_block);
        }
        {
            auto scope = w.indent_scope();
            MAYBE(block, ctx.visit(ctx.struct_decl.fields));
            w.write(block.to_writer());
            if (is_anon_inner) {
                MAYBE_VOID(_c, ebmcodegen::util::emit_struct_codec(ctx, w));
                MAYBE_VOID(_m, ebmcodegen::util::emit_struct_user_methods(ctx, w));
            }
            else {
                MAYBE_VOID(_self, ebmcodegen::util::emit_struct_methods(ctx, w));
                std::vector<ebm::WeakStatementRef> descendants;
                std::unordered_set<std::uint64_t> seen;
                ebm::WeakStatementRef self_weak{};
                self_weak.id = ctx.item_id;
                MAYBE_VOID(_collect, ebmcodegen::util::collect_anon_inner_descendants(ctx, self_weak, descendants, seen));
                for (auto& inner_ref : descendants) {
                    MAYBE(inner_stmt, ctx.get(from_weak(inner_ref)));
                    auto inner_decl_p = inner_stmt.body.struct_decl();
                    if (!inner_decl_p || !inner_decl_p->has_properties()) {
                        continue;
                    }
                    auto inner_props = inner_decl_p->properties();
                    if (!inner_props) {
                        continue;
                    }
                    for (auto& prop_ref : inner_props->container) {
                        MAYBE(prop_w, ctx.visit(prop_ref));
                        w.writeln(prop_w.to_writer());
                    }
                }
            }
        }
        w.writeln(ctx.config().end_block, ctx.config().endof_struct_definition);
        return w;
    };

    // Helper: format return type for a function declaration.
    // When the method is const (not mutable) AND returns a pointer type,
    // wrap the pointee with const (T* -> const T*) so that &member from within
    // the const method type-checks.
    auto format_return_type = [](Context_Statement_FUNCTION_DECL& ctx, Result ret_type) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(ret_type_info, ctx.get(ctx.func_decl.return_type));
        if (!ctx.func_decl.attribute.is_mutable() && ret_type_info.body.kind == ebm::TypeKind::PTR) {
            return CODE("const ", ret_type.to_writer());
        }
        return ret_type;
    };

    // Function declaration: phase-aware
    config.function_decl_custom = [format_return_type](Context_Statement_FUNCTION_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        auto phase = ctx.config().output_phase;
        if (phase == OutputPhase::Normal) {
            return pass;  // use default visitor flow (function_definition_start_wrapper handles it)
        }
        auto name = ctx.identifier();
        MAYBE(ret_type_raw, ctx.visit(ctx.func_decl.return_type));
        MAYBE(ret_type, format_return_type(ctx, ret_type_raw));
        CodeWriter params;
        for (const auto& param_ref : ctx.func_decl.params.container) {
            MAYBE(param, ctx.visit(param_ref));
            if (!params.empty()) {
                params.write(", ");
            }
            params.write(param.to_writer());
        }
        std::string prefix;
        if (ctx.func_decl.kind == ebm::FunctionKind::VECTOR_SETTER) {
            prefix = "set_";
        }
        // Inner-anon property accessors live on the outer (parent_format)
        // class but their method body references outer fields; prefix the
        // method name with the inner struct identifier so multiple branches
        // (and the merged accessor) don't collide as overloads.
        if (auto inner = hoisted_accessor_inner_ident(ctx)) {
            prefix = *inner + "_" + prefix;
        }
        std::string const_suffix = ctx.func_decl.attribute.is_mutable() ? "" : " const";
        // A function with no parent_format is a free function (e.g. an imported
        // module's top-level fn such as utf8.isUTF8). It must not be emitted as a
        // member of the module-wrapper struct (which would make it `tmp::isUTF8`
        // while the call site emits a plain `isUTF8(...)`). Emit the declaration
        // at file scope (via decl_toplevel) and the definition as a free function.
        if (is_nil(ctx.func_decl.parent_format)) {
            if (phase == OutputPhase::DeclarationOnly) {
                CodeWriter decl;
                decl.write(ret_type.to_writer(), " ", name, "(", params, ");");
                ctx.config().decl_toplevel.push_back(std::move(decl));
                return CodeWriter{};  // nothing goes inside the struct body
            }
            // FunctionBodyOnly: free function definition (no struct scope, no const)
            CodeWriter w;
            w.writeln(ret_type.to_writer(), " ", name, "(", params, ") {");
            {
                auto scope = w.indent_scope();
                MAYBE(body, ctx.visit(ctx.func_decl.body));
                w.write(body.to_writer());
            }
            w.writeln("}");
            return w;
        }
        CodeWriter w;
        if (phase == OutputPhase::DeclarationOnly) {
            // Emit signature only (no body)
            w.writeln(ret_type.to_writer(), " ", prefix, name, "(", params, ")", const_suffix, ";");
            // Also emit wrapper signature so it gets declared in the struct
            if (auto wrapper_ref = ctx.func_decl.wrapper_function()) {
                MAYBE(wrapper_sig, ctx.visit(*wrapper_ref));
                w.write(wrapper_sig.to_writer());
            }
            return w;
        }
        // FunctionBodyOnly: emit out-of-class definition
        auto struct_name = ctx.identifier(from_weak(ctx.func_decl.parent_format));
        w.writeln(ret_type.to_writer(), " ", struct_name, "::", prefix, name, "(", params, ")", const_suffix, " {");
        {
            auto scope = w.indent_scope();
            MAYBE(body, ctx.visit(ctx.func_decl.body));
            w.write(body.to_writer());
        }
        w.writeln("}");
        if (auto wrapper_ref = ctx.func_decl.wrapper_function()) {
            w.writeln();
            MAYBE(wrapper, ctx.visit(*wrapper_ref));
            w.write(wrapper.to_writer());
        }
        return w;
    };

    // Function definition start: used in Normal phase (default visitor path)
    config.function_definition_start_wrapper = [format_return_type](Result return_type, std::string_view name, CodeWriter params, Context_Statement_FUNCTION_DECL& ctx) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        MAYBE(ret_type, format_return_type(ctx, return_type));
        std::string prefix;
        if (ctx.func_decl.kind == ebm::FunctionKind::VECTOR_SETTER) {
            prefix = "set_";
        }
        // Same parent_struct-prefix rule as in function_decl_custom (see
        // there for rationale). Keeps the Normal-phase path consistent.
        if (auto inner = hoisted_accessor_inner_ident(ctx)) {
            prefix = *inner + "_" + prefix;
        }
        std::string const_suffix = ctx.func_decl.attribute.is_mutable() ? "" : " const";
        CodeWriter w;
        w.writeln(ret_type.to_writer(), " ", prefix, name, "(", params, ")", const_suffix, " {");
        return w;
    };

    // `const std::array<uint8_t, N> NAME = "string-literal"` doesn't
    // compile in C++ because string literals are const char[N+1]. Emit
    // brace-initialization with explicit byte values instead.
    config.byte_array_literal_wrapper = [](Context_Statement_VARIABLE_DECL& vctx, std::string_view name, size_t length, const std::string& bytes) -> expected<Result> {
        using namespace CODEGEN_NAMESPACE;
        CodeWriter w;
        w.write("constexpr std::array<std::uint8_t, ", std::format("{}", length), "> ", name, " = {");
        for (size_t i = 0; i < bytes.size(); i++) {
            if (i > 0) {
                w.write(", ");
            }
            w.write(std::format("0x{:02x}", static_cast<unsigned char>(bytes[i])));
        }
        w.writeln("};");
        return w;
    };

    return pass;
}
