name: Auto approve

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.user.login == github.repository_owner && 
      ! github.event.pull_request.draft
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v4
