# costom boilerplate file from sisakulint
name: Brgen Test Built Binary

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_call: null
  workflow_dispatch: null

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read

jobs:
  brgen-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Donload Artifact
        uses: actions/download-artifact@v4
        with:
          name: brgen-linux
          path: /tmp/brgen
      - name: Install Dependencies
        run: sudo apt-get install jq libc++-dev ninja-build -y
      - name: Run Brgen and Test
        run: |
          chmod -R +x /tmp/brgen
          cd /tmp/brgen
          . ./link_path.sh
          ldd /tmp/brgen/tool/src2json
          ldd /tmp/brgen/tool/libfutils.so
          /tmp/brgen/tool/src2json --version
          /tmp/brgen/tool/brgen
          git clone https://github.com/on-keyday/utils.git
          cd utils
          . build shared Debug futils
          cd ..
          export FUTILS_DIR=/tmp/brgen/utils
          # ./make_cpp_tests.sh ./ignore/example/test_info.json run
