# costom boilerplate file from sisakulint
name: Brgen Test Built Binary

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_call: null
  workflow_dispatch: null

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read

jobs:
  brgen-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@427ee2cf860166e404d0d69b4f2b24012bb7af4f # v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Donload Artifact
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
        with:
          name: brgen-linux
          path: /tmp/brgen
      - name: Install Dependencies
        run: sudo apt-get install jq libc++-dev ninja-build -y
      - name: Run Brgen
        run: |
          chmod -R +x /tmp/brgen
          cd /tmp/brgen
          . ./link_path.sh
          ldd /tmp/brgen/tool/src2json
          ldd /tmp/brgen/tool/libfutils.so
          /tmp/brgen/tool/src2json --version
          /tmp/brgen/tool/brgen -debug
      - name: Clone Utils
        run: |
          cd /tmp/brgen
          git clone https://github.com/on-keyday/utils.git
          mkdir utils/lib
          cp tool/libfutils.so utils/lib
      - name: Test
        run: |
          cd /tmp/brgen
          . ./link_path.sh
          FUTILS_DIR=/tmp/brgen/utils tool/cmptest -f ignore/example/test_info.json -c testkit/cmptest.json --expected-test-total 8 --debug
