# costom boilerplate file from sisakulint
name: Brgen Test Built Binary

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_call: null
  workflow_dispatch: null

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read

jobs:
  brgen-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@a7eaabf426cdae26c3582c3fa674b897170dec8f # v2.2.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Donload Artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: brgen-linux
          path: /tmp/brgen
      - name: Install Dependencies
        run: sudo apt-get install jq libc++-dev ninja-build -y
      - name: Run Brgen
        run: |
          chmod -R +x /tmp/brgen
          cd /tmp/brgen
          . ./link_path.sh
          ldd /tmp/brgen/tool/src2json
          ldd /tmp/brgen/tool/libfutils.so
          /tmp/brgen/tool/src2json --version
          /tmp/brgen/tool/brgen -debug
      - name: Clone Utils
        run: |
          cd /tmp/brgen
          git clone https://github.com/on-keyday/utils.git
          mkdir utils/lib
          cp tool/libfutils.so utils/lib
      - name: Test
        run: |
          cd /tmp/brgen
          . ./link_path.sh
          FUTILS_DIR=/tmp/brgen/utils tool/cmptest -f ignore/example/test_info.json -c testkit/cmptest.json --expected-test-total 8 --debug
