name: brgen-build
run-name: Build
on: push

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        env: ["llvm", "gcc"]
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@7e868db0f3406270dd46e1dac26c65f621456723 # master
      - name: Set up Clang
        uses: egor-tensin/setup-clang@ef434b41eb33a70396fb336b1bae39c76d740c3d # v1.4
        with:
          version: latest
          platform: x64
      - name: Install libc++-dev and libc++abi-dev
        run: sudo apt-get install libc++-dev libc++abi-dev -y
        if: matrix.env == 'llvm'
      - name: Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        # prevent renovate from updating this
        if: (!startsWith(github.ref , 'refs/heads/renovate/')) && (!startsWith(github.ref , 'refs/heads/dependabot/'))
        id: cache_linux
        env:
          cache-name: cache-linux-built-${{ matrix.env }}
        with:
          path: |
            ./built
            ./utils
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('build.sh') }}-${{ matrix.env }}
      - name: Pull Utils
        if: ${{ steps.cache_linux.outputs.cache-hit }}
        run: |
          cd utils
          git pull
          # default is llvm
          if [ "${{ matrix.env }}" = "gcc" ]; then
            export FUTILS_CXX_COMPILER=g++
            export FUTILS_C_COMPILER=gcc
          fi
          . build shared Release futils
          cd ..
      - name: Build
        run: |
          # default is llvm
          if [ "${{ matrix.env }}" = "gcc" ]; then
            export FUTILS_CXX_COMPILER=g++
            export FUTILS_C_COMPILER=gcc
          fi
          . build.sh native Release
          ./tool/src2json --version
      - name: Pack artifacts
        run: |
          mkdir -p artifacts
          cp -a ./tool ./artifacts/tool
          cp -a ./script/link_path.sh ./artifacts
          cp -a ./example ./artifacts/example
          cp -a ./LICENSE ./artifacts
          cp -a ./README.md ./artifacts
          cp -a ./brgen.json ./artifacts
          cp -a ./script/make_cpp_test.sh ./artifacts
          cp -a ./script/make_cpp_tests.sh ./artifacts
          cp -a ./testkit ./artifacts/testkit
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: brgen-linux-${{ matrix.env }}
          path: ./artifacts
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@7e868db0f3406270dd46e1dac26c65f621456723 # master
      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: ">=1.20"
      - name: Install Homebrew Clang
        run: |
          brew install llvm
      - name: Check Code
        run: |
          PREFIX=$(brew --prefix llvm)
          # from https://github.com/llvm/llvm-project/issues/77786
          LIBCPP=$PREFIX/lib/c++
          ls $LIBCPP
          echo "libc++"
          nm $LIBCPP/libc++.1.dylib | c++filt
          echo "libc++abi"
          nm $LIBCPP/libc++abi.1.dylib | c++filt
      - name: Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        # prevent renovate from updating this
        if: (!startsWith(github.ref , 'refs/heads/renovate/')) && (!startsWith(github.ref , 'refs/heads/dependabot/'))
        id: cache_macos
        env:
          cache-name: cache-macos-built
        with:
          path: |
            ./built
            ./utils
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('build.sh') }}
      - name: Pull Utils
        if: ${{ steps.cache_macos.outputs.cache-hit }}
        run: |
          cd utils
          git pull
          PREFIX=$(brew --prefix llvm)
          export FUTILS_CXX_COMPILER=$PREFIX/bin/clang++
          export FUTILS_C_COMPILER=$PREFIX/bin/clang
          export LDFLAGS="-L$PREFIX/lib/c++ -L$PREFIX/lib/unwind -lunwind -Wl,-rpath,$PREFIX/lib/c++"
          . build shared Release futils
          cd ..
      - name: Build
        run: |
          PREFIX=$(brew --prefix llvm)
          export FUTILS_CXX_COMPILER=$PREFIX/bin/clang++
          export FUTILS_C_COMPILER=$PREFIX/bin/clang
          export LDFLAGS="-L$PREFIX/lib/c++ -L$PREFIX/lib/unwind -lunwind -Wl,-rpath,$PREFIX/lib/c++"
          . build.sh native Release
          ./tool/src2json --version
      - name: Pack artifacts
        run: |
          mkdir -p artifacts
          cp -a ./tool ./artifacts/tool
          cp -a ./script/link_path.sh ./artifacts
          cp -a ./example ./artifacts/example
          cp -a ./LICENSE ./artifacts
          cp -a ./README.md ./artifacts
          cp -a ./brgen.json ./artifacts
          cp -a ./script/make_cpp_test.sh ./artifacts
          cp -a ./script/make_cpp_tests.sh ./artifacts
          cp -a ./testkit ./artifacts/testkit
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: brgen-macos
          path: ./artifacts

  build-windows:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@7e868db0f3406270dd46e1dac26c65f621456723 # master
      - name: Set up Clang
        uses: egor-tensin/setup-clang@ef434b41eb33a70396fb336b1bae39c76d740c3d # v1.4
        with:
          version: latest
          platform: x64
      - name: Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache_windows
        # prevent renovate from updating this
        if: (!startsWith(github.ref , 'refs/heads/renovate/')) && (!startsWith(github.ref , 'refs/heads/dependabot/'))
        env:
          cache-name: cache-windows-built
        with:
          path: |
            ./built
            ./utils
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('build.bat') }}
      - name: Pull Utils
        if: ${{ steps.cache_windows.outputs.cache-hit }}
        shell: cmd
        run: |
          cd utils
          git pull
          build shared Release futils
          cd ..
      - name: Build
        shell: cmd
        run: |
          call .\build.bat native Release %CD%\utils
          .\tool\src2json.exe --version
      - name: Pack artifacts
        shell: cmd
        run: |
          mkdir artifacts
          xcopy /E /I /Y tool artifacts\tool
          xcopy /E /I /Y example artifacts\example
          copy /Y LICENSE artifacts
          copy /Y README.md artifacts
          copy /Y brgen.json artifacts
          copy /Y script\make_cpp_test.bat artifacts
          copy /Y script\make_cpp_tests.bat artifacts
          xcopy /E /I /Y testkit artifacts\testkit
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: brgen-windows
          path: ./artifacts

  build-vscode-extension:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      - name: Setup ast2ts
        run: |
          cd astlib/ast2ts
          npm install
          tsc
          cd ../..
      - name: Install VSCE
        run: npm install -g vsce
      - name: Build
        run: |
          cd lsp
          npm install
          vsce package
      - name: Pack artifacts
        run: |
          mkdir -p artifacts
          cp -a ./lsp/LICENSE ./artifacts
          cp -a ./lsp/brgen-lsp-*.vsix ./artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: brgen-vscode-extension
          path: ./artifacts

  build-arm-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@7e868db0f3406270dd46e1dac26c65f621456723 # master
      - name: Install Cross Compiler
        run: |
          sudo apt-get update && sudo apt-get install -y g++-aarch64-linux-gnu
      - name: Build
        run: |
          go version
          export GOARCH=arm64
          export FUTILS_CXX_COMPILER=aarch64-linux-gnu-g++
          export FUTILS_C_COMPILER=aarch64-linux-gnu-gcc
          export CC=$FUTILS_C_COMPILER
          . build.sh native Release
      - name: Pack artifacts
        run: |
          mkdir -p artifacts
          cp -a ./tool ./artifacts/tool
          cp -a ./script/link_path.sh ./artifacts
          cp -a ./example ./artifacts/example
          cp -a ./LICENSE ./artifacts
          cp -a ./README.md ./artifacts
          cp -a ./brgen.json ./artifacts
          cp -a ./script/make_cpp_test.sh ./artifacts
          cp -a ./script/make_cpp_tests.sh ./artifacts
          cp -a ./testkit ./artifacts/testkit
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: brgen-linux-arm
          path: ./artifacts

  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@7e868db0f3406270dd46e1dac26c65f621456723 # master
      - name: Install Android NDK
        uses: nttld/setup-ndk@afb4c9964b521afb97c864b7d40b11e6911bd410 # v1.5.0
        with:
          ndk-version: r26b
      - name: Build
        run: |
          BASE_PATH=/opt/hostedtoolcache/ndk/r26b/x64/toolchains/llvm/prebuilt/linux-x86_64
          #ls -Ral $BASE_PATH
          export GOARCH=arm64
          export FUTILS_CXX_COMPILER=$BASE_PATH/bin/aarch64-linux-android21-clang++
          export FUTILS_C_COMPILER=$BASE_PATH/bin/aarch64-linux-android21-clang
          export CC=$FUTILS_C_COMPILER
          . build.sh native Release
          LIBCPP_SHARED=$BASE_PATH/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so 
          cp $LIBCPP_SHARED ./tool
      - name: Pack artifacts
        run: |
          mkdir -p artifacts
          cp -a ./tool ./artifacts/tool
          cp -a ./script/link_path.sh ./artifacts
          cp -a ./example ./artifacts/example
          cp -a ./LICENSE ./artifacts
          cp -a ./README.md ./artifacts
          cp -a ./brgen.json ./artifacts
          cp -a ./script/make_cpp_test.sh ./artifacts
          cp -a ./script/make_cpp_tests.sh ./artifacts
          cp -a ./testkit ./artifacts/testkit
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: brgen-android
          path: ./artifacts

  collect-licenses:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: fetch dependencies
        run: |
          go mod download
          cd astlib/ast2ts
          npm install
          tsc
          cp ../../LICENSE ./out
          cd ../../lsp
          npm install
          cd server
          npm install
          cd ../client
          npm install
          cd ../../src/tool/json2rust
          mkdir -p ./pkg
          cp ../../../LICENSE ./pkg
          cd ../../../web/doc
          go mod download
          cd ../dev
          npm install
          cd ../..
      - name: Install gocredits
        run: |
          go install github.com/Songmu/gocredits/cmd/gocredits@latest
      - name: Set up ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          ruby-version: ruby
      - uses: github/setup-licensed@be11bcbb82e3140b6cf260e647c3efeeca8fcefd # v1.3.1
        with:
          version: "4.4" # required: supports matching based on string equivalence or node-semver range
      - name: Collect licenses
        run: |
          go mod edit -json
          . ./script/collect_licenses.sh
      - name: List licenses
        run: |
          ls -alR ./license_cache
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: brgen-licenses
          path: ./license_cache

  build-pages:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        env: ["development", "production"]
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@54d513e0b5ff1158f1cf8321108d666a5a6c1fca # v2.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021 # v14
        #with:
        #  actions-cache-folder: emsdk
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@7e868db0f3406270dd46e1dac26c65f621456723 # master
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.25"
      - name: Cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        # prevent renovate from updating this
        if: (!startsWith(github.ref , 'refs/heads/renovate/')) && (!startsWith(github.ref , 'refs/heads/dependabot/'))
        id: cache_web
        env:
          cache-name: cache-web-built
        with:
          path: |
            ./built
            ./utils
            ./astlib/ast2ts/node_modules
            ./web/dev/node_modules
          # ./emsdk
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('build.sh') }}
      - name: Pull Utils
        if: ${{ steps.cache_web.outputs.cache-hit }}
        run: |
          cd utils
          git pull
          rm -rf built
          if [ "${{ matrix.env }}" = "production" ]; then
          MODE=Release
          else
          MODE=Debug
          fi
          . build wasm-em $MODE futils
          cd ..
      - name: Set up ast2ts
        run: |
          cd astlib/ast2ts
          npm install
          tsc
          cd ../..
      - name: Set up wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Fetch rebrgen artifacts
        run: |
          chmod +x ./script/fetch_rebrgen.sh
          ./script/fetch_rebrgen.sh
          ls -alR ./web/dev/src/lib
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Wasm
        run: |
          GOROOT=`go env GOROOT`
          echo "GOROOT=$GOROOT"
          export WASMEXEC_FILE="$GOROOT/lib/wasm/wasm_exec.js"
          if [ ! -e "$WASMEXEC_FILE" ]; then
            echo "$WASMEXEC_FILE not found"
            exit 1
          fi
          export WEB_PRODUCTION=${{ matrix.env }}
          echo "WEB_PRODUCTION=$WEB_PRODUCTION"
          rm -rf built
          if [ "${{ matrix.env }}" = "production" ]; then
            MODE=Release
          else
            MODE=Debug
          fi
          . build.sh wasm-em $MODE
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: "latest"
          extended: true
      - name: Build Hugo
        run: |
          cd web/doc
          hugo --minify
          cd ../..
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: brgen-web-${{ matrix.env }}
          path: "./web/public"
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
        if: matrix.env == 'production'

  run-test:
    needs: build-linux
    uses: ./.github/workflows/brgen-test.yaml

  puppeteer-test:
    needs: build-pages
    uses: ./.github/workflows/puppeteer-test.yml
  release:
    needs:
      [
        build-linux,
        build-macos,
        build-windows,
        build-vscode-extension,
        build-arm-linux,
        build-android,
        build-pages,
        collect-licenses,
        run-test,
        puppeteer-test,
      ]
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write

  deploy:
    needs: puppeteer-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      pages: write
      id-token: write
