name: brgen-test
run-name: brgen test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Timeline
        uses: Kesin11/actions-timeline@v1
        with:
          # e.g.: ${{ secrets.MY_PAT }}
          # Default: ${{ github.token }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1.4
        with:
          version: latest
          platform: x64
      - name: Build
        run: |
          . build.sh
      - name: Test
        run: |
          CTEST_OUTPUT_ON_FAILURE=1 BASE_PATH=${{ github.workspace }} ninja -C built/native/Debug test
