/*DO NOT EDIT BELOW SECTION MANUALLY*/
/*license*/
// Template generated by ebmcodegen at https://github.com/on-keyday/brgen
/*
  Name: Expression_LITERAL_INT64_before_class
  Available Variables:
    ctx: Context_Expression_LITERAL_INT64_before<Result>
      visitor: MergedVisitor&
        program_name: static constexpr const char*
        flags: Flags&
        output: Output&
        wm: ebmcodegen::WriterManager<CodeWriter>
        module_: ebmgen::MappingTable
      item_id: ebm::ExpressionRef
      type: const ebm::TypeRef&
      kind: const ebm::ExpressionKind&
      int64_value: const std::uint64_t&
      main_logic: ebmcodegen::util::MainLogicWrapper<Result>
*/
/*DO NOT EDIT ABOVE SECTION MANUALLY*/


#include "../codegen.hpp"

// LITERAL_INT64 fires for integer literals the EBM has typed as a >= 64-bit
// home (whatever the literal *value* fits). When --use-bigint is set and
// that home renders as bigint, emit the JS `n` suffix; otherwise the
// surrounding bigint operands raise "Cannot mix BigInt and other types".
DEFINE_VISITOR(Expression_LITERAL_INT64_before) {
    using namespace CODEGEN_NAMESPACE;
    if (!ctx.flags().use_bigint) {
        return Result(std::to_string(ctx.int64_value));
    }
    MAYBE(t, ctx.get(ctx.type));
    const auto k = t.body.kind;
    if (k != ebm::TypeKind::INT && k != ebm::TypeKind::UINT) {
        return Result(std::to_string(ctx.int64_value));
    }
    std::uint64_t bits = 0;
    if (auto sz = t.body.size()) {
        bits = sz->value();
    }
    if (bits <= 32) {
        return Result(std::to_string(ctx.int64_value));
    }
    return Result(std::format("{}n", ctx.int64_value));
}

